# Form implementation for the Shifter Unit mask dialog.
# Hand-generated by casper_dsp/scripts/gen_block_gui.py to match the layout
# in ui/shifter_unit.ui -- if PyQt6/pyuic6 is available, regenerate with:
#   pyuic6 ui/shifter_unit.ui -o shifter_unit_ui.py
# and keep both in sync by hand otherwise.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(560, 280)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)

        self.desc_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.desc_label.setWordWrap(True)
        self.desc_label.setObjectName("desc_label")
        self.verticalLayout.addWidget(self.desc_label)

        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout.setColumnStretch(1, 1)
        self.label_data_width = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_data_width.setObjectName("label_data_width")
        self.label_data_width.setWordWrap(True)
        self.label_data_width.setFixedWidth(94)
        self.gridLayout.addWidget(self.label_data_width, 1, 0, 1, 1)
        self.data_width = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.data_width.setObjectName("data_width")
        self.data_width.setRange(1, 8192)
        self.gridLayout.addWidget(self.data_width, 1, 1, 1, 2)
        self.label_pin_offset = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_pin_offset.setObjectName("label_pin_offset")
        self.label_pin_offset.setWordWrap(True)
        self.label_pin_offset.setFixedWidth(94)
        self.gridLayout.addWidget(self.label_pin_offset, 2, 0, 1, 1)
        self.pin_offset = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.pin_offset.setObjectName("pin_offset")
        self.pin_offset.setRange(0, 100000)
        self.gridLayout.addWidget(self.pin_offset, 2, 1, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.buttonLayout.addItem(spacerItem)
        self.button_apply = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_apply.setObjectName("button_apply")
        self.buttonLayout.addWidget(self.button_apply)
        self.button_ok = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_ok.setObjectName("button_ok")
        self.buttonLayout.addWidget(self.button_ok)
        self.button_cancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_cancel.setObjectName("button_cancel")
        self.buttonLayout.addWidget(self.button_cancel)
        self.verticalLayout.addLayout(self.buttonLayout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Shifter Unit"))
        self.title_label.setText(_translate("MainWindow", "Shifter Unit"))
        self.desc_label.setText(_translate("MainWindow", "This block is simply a wrapper for a register with a multiplexer on the input. Please see the documentation for the 'parallel_to_serial_converter'."))
        self.label_data_width.setText(_translate("MainWindow", "Data Width"))
        self.label_pin_offset.setText(_translate("MainWindow", "pin offset"))
        self.button_apply.setText(_translate("MainWindow", "Apply"))
        self.button_ok.setText(_translate("MainWindow", "OK"))
        self.button_cancel.setText(_translate("MainWindow", "Cancel"))
