# Form implementation for the DAC MKID Interface mask dialog.
# Hand-generated by casper_xps/scripts/gen_block_gui.py to match the layout
# in ui/dac_mkid.ui -- if PyQt6/pyuic6 is available, regenerate with:
#   pyuic6 ui/dac_mkid.ui -o dac_mkid_ui.py
# and keep both in sync by hand otherwise.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(627, 320)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)

        self.desc_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.desc_label.setWordWrap(True)
        self.desc_label.setObjectName("desc_label")
        self.verticalLayout.addWidget(self.desc_label)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout.setColumnStretch(1, 1)
        self.label_dac_brd = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_dac_brd.setObjectName("label_dac_brd")
        self.label_dac_brd.setWordWrap(True)
        self.label_dac_brd.setFixedWidth(227)
        self.gridLayout.addWidget(self.label_dac_brd, 1, 0, 1, 1)
        self.dac_brd = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.dac_brd.setObjectName("dac_brd")
        self.dac_brd.addItem("")
        self.dac_brd.addItem("")
        self.gridLayout.addWidget(self.dac_brd, 1, 1, 1, 2)
        self.label_dac_clk_rate = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_dac_clk_rate.setObjectName("label_dac_clk_rate")
        self.label_dac_clk_rate.setWordWrap(True)
        self.label_dac_clk_rate.setFixedWidth(227)
        self.gridLayout.addWidget(self.label_dac_clk_rate, 2, 0, 1, 1)
        self.dac_clk_rate = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.dac_clk_rate.setObjectName("dac_clk_rate")
        self.gridLayout.addWidget(self.dac_clk_rate, 2, 1, 1, 2)
        self.label_sample_period = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_sample_period.setObjectName("label_sample_period")
        self.label_sample_period.setWordWrap(True)
        self.label_sample_period.setFixedWidth(227)
        self.gridLayout.addWidget(self.label_sample_period, 3, 0, 1, 1)
        self.sample_period = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.sample_period.setObjectName("sample_period")
        self.gridLayout.addWidget(self.sample_period, 3, 1, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.buttonLayout.addItem(spacerItem)
        self.button_apply = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_apply.setObjectName("button_apply")
        self.buttonLayout.addWidget(self.button_apply)
        self.button_ok = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_ok.setObjectName("button_ok")
        self.buttonLayout.addWidget(self.button_ok)
        self.button_cancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_cancel.setObjectName("button_cancel")
        self.buttonLayout.addWidget(self.button_cancel)
        self.verticalLayout.addLayout(self.buttonLayout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DAC MKID Interface"))
        self.title_label.setText(_translate("MainWindow", "DAC MKID Interface"))
        self.desc_label.setText(_translate("MainWindow", "Interface block for the MKID 16-bits DAC board (2xDAC5681)"))
        self.label_dac_brd.setText(_translate("MainWindow", "DAC board"))
        self.dac_brd.setItemText(0, _translate("MainWindow", "0"))
        self.dac_brd.setItemText(1, _translate("MainWindow", "1"))
        self.label_dac_clk_rate.setText(_translate("MainWindow", "DAC external clock rate (MHz)"))
        self.label_sample_period.setText(_translate("MainWindow", "Sample period"))
        self.button_apply.setText(_translate("MainWindow", "Apply"))
        self.button_ok.setText(_translate("MainWindow", "OK"))
        self.button_cancel.setText(_translate("MainWindow", "Cancel"))
