# Form implementation for the IP mask dialog.
# Hand-generated by casper_xps/scripts/gen_block_gui.py to match the layout
# in ui/ip.ui -- if PyQt6/pyuic6 is available, regenerate with:
#   pyuic6 ui/ip.ui -o ip_ui.py
# and keep both in sync by hand otherwise.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(851, 310)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)

        self.desc_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.desc_label.setWordWrap(True)
        self.desc_label.setObjectName("desc_label")
        self.verticalLayout.addWidget(self.desc_label)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout.setColumnStretch(1, 1)
        self.label_name = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_name.setObjectName("label_name")
        self.label_name.setWordWrap(True)
        self.label_name.setFixedWidth(451)
        self.gridLayout.addWidget(self.label_name, 1, 0, 1, 1)
        self.name = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 1, 1, 1, 2)
        self.label_lib_path = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_lib_path.setObjectName("label_lib_path")
        self.label_lib_path.setWordWrap(True)
        self.label_lib_path.setFixedWidth(451)
        self.gridLayout.addWidget(self.label_lib_path, 2, 0, 1, 1)
        self.lib_path = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.lib_path.setObjectName("lib_path")
        self.gridLayout.addWidget(self.lib_path, 2, 1, 1, 2)
        self.label_ip_name = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_ip_name.setObjectName("label_ip_name")
        self.label_ip_name.setWordWrap(True)
        self.label_ip_name.setFixedWidth(451)
        self.gridLayout.addWidget(self.label_ip_name, 3, 0, 1, 1)
        self.ip_name = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.ip_name.setObjectName("ip_name")
        self.gridLayout.addWidget(self.ip_name, 3, 1, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.buttonLayout.addItem(spacerItem)
        self.button_apply = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_apply.setObjectName("button_apply")
        self.buttonLayout.addWidget(self.button_apply)
        self.button_ok = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_ok.setObjectName("button_ok")
        self.buttonLayout.addWidget(self.button_ok)
        self.button_cancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_cancel.setObjectName("button_cancel")
        self.buttonLayout.addWidget(self.button_cancel)
        self.verticalLayout.addLayout(self.buttonLayout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "IP"))
        self.title_label.setText(_translate("MainWindow", "IP"))
        self.desc_label.setText(_translate("MainWindow", "Allows insertion of custom Xilinx IP content from user created libraries."))
        self.label_name.setText(_translate("MainWindow", "Block name"))
        self.name.setToolTip(_translate("MainWindow", "A name you choose for this block instance, e.g. to note what it's used for in this design. Shown below the block on the diagram."))
        self.label_lib_path.setText(_translate("MainWindow", "Path to sysgen build directory (the directory containing ip/)"))
        self.label_ip_name.setText(_translate("MainWindow", "Name of IP in this library"))
        self.button_apply.setText(_translate("MainWindow", "Apply"))
        self.button_ok.setText(_translate("MainWindow", "OK"))
        self.button_cancel.setText(_translate("MainWindow", "Cancel"))
