// adc: Xcos block definition, PyQt6-mask pattern.
// Generated by casper_xps/scripts/gen_sci_block.py -- review the port
// Port list confirmed against the real xps_library/xps_models/ADCs/adc.slx
// standalone model (Ports=[3,17]): adc_mask.m never calls reuse_block/
// sets model.in/model.out -- it only renames existing Gateway blocks --
// so the port set is static, taken directly from the block's own
// top-level Inport/Outport children. Widths are a best-effort inference
// from the mask description ("digitized to 8 bit"); i0-i3/q0-q3 are 8-bit,
// outofrange*/sync*/data_valid are 1-bit flags, sim_in/sim_sync/
// sim_data_valid widths are not confirmed against real hardware docs.
// topology and TODOs below before relying on this in a real design.
function [x, y, typ] = adc(job, arg1, arg2)
    x=[];y=[];typ=[];
    select job
    case 'set' then
        x = arg1;
        export_exprs_to_tmpdir(x);
        bconfig = run_mask(x);
        x = update_exprs_from_tmpdir(x);
        x = adc_update_ports(x, bconfig);
    case 'define' then
        tag = 'adc';
        model = scicos_model();
        model.sim = list(tag, 4);
        model.blocktype = 'c';
        model.rpar = [];
        exprs = [];
        gr_i = [];
        model.in = [1, 2, 3];
        model.in2 = [8, 1, 1];
        model.out = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17];
        model.out2 = [8, 8, 8, 8, 8, 8, 8, 8, 1, 1, 1, 1, 1, 1, 1, 1, 1];
        // model.label doubles as the on-diagram display text (Scicos
        // aliases it with graphics.id); category is derived separately by
        // get_block_type.sci via file-probe, so this is free to be the name.
        model.label = tag;
        x=standard_define([15.6 28.8],model,exprs,gr_i)
        x.graphics.in_label = ['sim_in', 'sim_sync', 'sim_data_valid'];
        x.graphics.out_label = ['i0', 'i1', 'i2', 'i3', 'q0', 'q1', 'q2', 'q3', 'outofrangei0', 'outofrangei1', 'outofrangeq0', 'outofrangeq1', 'sync0', 'sync1', 'sync2', 'sync3', 'data_valid'];
        x.graphics.style = 'shape=rectangle;fillColor=yellow';
        /* init exprs */
        x = init_exprs(x);
        debug_info('adc block loaded...')
    end
endfunction

function [x] = adc_update_ports(obj, bconfigfn)
    // fixed port count: only widths/labels change, no set_io() needed
    // (same approach as swreg_update_ports)
    x = obj;
    bconfig = fromJSON(bconfigfn, 'file');
    p = bconfig('parameters');
    graphics = x.graphics;
    model = x.model;
    model.in = [1, 2, 3];
    model.in2 = [8, 1, 1];
    model.out = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17];
    model.out2 = [8, 8, 8, 8, 8, 8, 8, 8, 1, 1, 1, 1, 1, 1, 1, 1, 1];
    graphics.in_label = ['sim_in', 'sim_sync', 'sim_data_valid'];
    graphics.out_label = ['i0', 'i1', 'i2', 'i3', 'q0', 'q1', 'q2', 'q3', 'outofrangei0', 'outofrangei1', 'outofrangeq0', 'outofrangeq1', 'sync0', 'sync1', 'sync2', 'sync3', 'data_valid'];
    graphics.style = 'shape=rectangle;fillColor=yellow';
    x.graphics = graphics;
    x.model = model;
endfunction
