// adc1x1800_10: Xcos block definition, PyQt6-mask pattern.
// Generated by casper_xps/scripts/gen_sci_block.py -- review the port
// Port list confirmed against the real xps_library/xps_models/ADCs/
// adc1x1800_10.slx standalone model (Ports=[4,18]): mkadc_mask.m only
// renames existing Gateway blocks, never builds ports dynamically, so
// this is the block's own real static port set. o0-o7 are 10-bit
// ("Max 1.8G Sample, 10bit" per the mask description); outofrange*/sync/
// data_valid are 1-bit flags; sim_in/sim_sync/sim_data_valid/
// demux_tst_pat_en widths are a best-effort guess, not confirmed.
// topology and TODOs below before relying on this in a real design.
function [x, y, typ] = adc1x1800_10(job, arg1, arg2)
    x=[];y=[];typ=[];
    select job
    case 'set' then
        x = arg1;
        export_exprs_to_tmpdir(x);
        bconfig = run_mask(x);
        x = update_exprs_from_tmpdir(x);
        x = adc1x1800_10_update_ports(x, bconfig);
    case 'define' then
        tag = 'adc1x1800_10';
        model = scicos_model();
        model.sim = list(tag, 4);
        model.blocktype = 'c';
        model.rpar = [];
        exprs = [];
        gr_i = [];
        model.in = [1, 2, 3, 4];
        model.in2 = [10, 1, 1, 1];
        model.out = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18];
        model.out2 = [10, 10, 10, 10, 10, 10, 10, 10, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1];
        // model.label doubles as the on-diagram display text (Scicos
        // aliases it with graphics.id); category is derived separately by
        // get_block_type.sci via file-probe, so this is free to be the name.
        model.label = tag;
        x=standard_define([19.2 39.6],model,exprs,gr_i)
        x.graphics.in_label = ['sim_in', 'sim_sync', 'sim_data_valid', 'demux_tst_pat_en'];
        x.graphics.out_label = ['o0', 'o1', 'o2', 'o3', 'o4', 'o5', 'o6', 'o7', 'outofrange0', 'outofrange1', 'outofrange2', 'outofrange3', 'outofrange4', 'outofrange5', 'outofrange6', 'outofrange7', 'sync', 'data_valid'];
        x.graphics.style = 'shape=rectangle;fillColor=yellow';
        /* init exprs */
        x = init_exprs(x);
        debug_info('adc1x1800_10 block loaded...')
    end
endfunction

function [x] = adc1x1800_10_update_ports(obj, bconfigfn)
    // fixed port count: only widths/labels change, no set_io() needed
    // (same approach as swreg_update_ports)
    x = obj;
    bconfig = fromJSON(bconfigfn, 'file');
    p = bconfig('parameters');
    graphics = x.graphics;
    model = x.model;
    model.in = [1, 2, 3, 4];
    model.in2 = [10, 1, 1, 1];
    model.out = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18];
    model.out2 = [10, 10, 10, 10, 10, 10, 10, 10, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1];
    graphics.in_label = ['sim_in', 'sim_sync', 'sim_data_valid', 'demux_tst_pat_en'];
    graphics.out_label = ['o0', 'o1', 'o2', 'o3', 'o4', 'o5', 'o6', 'o7', 'outofrange0', 'outofrange1', 'outofrange2', 'outofrange3', 'outofrange4', 'outofrange5', 'outofrange6', 'outofrange7', 'sync', 'data_valid'];
    graphics.style = 'shape=rectangle;fillColor=yellow';
    x.graphics = graphics;
    x.model = model;
endfunction
