// adc2x14_400: Xcos block definition, PyQt6-mask pattern.
// Generated by casper_xps/scripts/gen_sci_block.py -- review the port
// Port list confirmed against the real xps_library/xps_models/ADCs/
// adc2x14_400.slx standalone model (Ports=[0,5]): adc2x14_400_mask.m only
// renames existing Gateway blocks (user_data_i0/i1/q0/q1/user_sync), never
// builds ports dynamically -- data_i0/i1/q0/q1/sync is the block's own real
// static port set. Data widths are 14-bit per the mask description
// ("Interface block for the MKID 14-bits 400 MHz ADC board"); sync is 1-bit.
// topology and TODOs below before relying on this in a real design.
function [x, y, typ] = adc2x14_400(job, arg1, arg2)
    x=[];y=[];typ=[];
    select job
    case 'set' then
        x = arg1;
        export_exprs_to_tmpdir(x);
        bconfig = run_mask(x);
        x = update_exprs_from_tmpdir(x);
        x = adc2x14_400_update_ports(x, bconfig);
    case 'define' then
        tag = 'adc2x14_400';
        model = scicos_model();
        model.sim = list(tag, 4);
        model.blocktype = 'c';
        model.rpar = [];
        exprs = [];
        gr_i = [];
        model.in = [];
        model.in2 = [];
        model.out = [1, 2, 3, 4, 5];
        model.out2 = [14, 14, 14, 14, 1];
        // model.label doubles as the on-diagram display text (Scicos
        // aliases it with graphics.id); category is derived separately by
        // get_block_type.sci via file-probe, so this is free to be the name.
        model.label = tag;
        x=standard_define([8.4 27.6],model,exprs,gr_i)
        x.graphics.in_label = [];
        x.graphics.out_label = ['data_i0', 'data_i1', 'data_q0', 'data_q1', 'sync'];
        /* init exprs */
        x = init_exprs(x);
        x.graphics.style = adc2x14_400_build_style(x.graphics.exprs(1));
        debug_info('adc2x14_400 block loaded...')
    end
endfunction

/* build the graphics.style string for a given user-configurable block
   name, showing it below the yellow fill (see displayedLabel). Strips
   ';' and '=' from the name since those are the mxGraph style string's
   own delimiter characters -- an unescaped one would corrupt every key
   after it in the style string, not just truncate the label. */
function [style] = adc2x14_400_build_style(name)
    name = strsubst(string(name), ';', '');
    name = strsubst(name, '=', '');
    style = 'shape=rectangle;fillColor=yellow;strokeColor=black;fontColor=black;fontSize=12;align=center;verticalAlign=top;verticalLabelPosition=bottom;noLabel=0;displayedLabel=' + name + ';whiteSpace=wrap;html=1;spacing=4;';
endfunction

function [x] = adc2x14_400_update_ports(obj, bconfigfn)
    // fixed port count: only widths/labels change, no set_io() needed
    // (same approach as swreg_update_ports)
    x = obj;
    bconfig = fromJSON(bconfigfn, 'file');
    p = bconfig('parameters');
    graphics = x.graphics;
    model = x.model;
    model.in = [];
    model.in2 = [];
    model.out = [1, 2, 3, 4, 5];
    model.out2 = [14, 14, 14, 14, 1];
    graphics.in_label = [];
    graphics.out_label = ['data_i0', 'data_i1', 'data_q0', 'data_q1', 'sync'];
    graphics.style = adc2x14_400_build_style(p('name'));
    x.graphics = graphics;
    x.model = model;
endfunction
