// adc_mkid: Xcos block definition, PyQt6-mask pattern.
// Generated by casper_xps/scripts/gen_sci_block.py -- review the port
// Port list confirmed against the real xps_library/xps_models/ADCs/
// adc_mkid.slx standalone model (Ports=[0,5]): adc_mkid_mask.m only
// renames existing Gateway blocks, never builds ports dynamically --
// data_i0/i1/q0/q1/sync is the block's own real static port set (same
// shape as adc2x14_400). Data widths are 12-bit per the mask description
// ("MKID 12-bits 550 MHz ADC board"); sync is 1-bit.
// topology and TODOs below before relying on this in a real design.
function [x, y, typ] = adc_mkid(job, arg1, arg2)
    x=[];y=[];typ=[];
    select job
    case 'set' then
        x = arg1;
        export_exprs_to_tmpdir(x);
        bconfig = run_mask(x);
        x = update_exprs_from_tmpdir(x);
        x = adc_mkid_update_ports(x, bconfig);
    case 'define' then
        tag = 'adc_mkid';
        model = scicos_model();
        model.sim = list(tag, 4);
        model.blocktype = 'c';
        model.rpar = [];
        exprs = [];
        gr_i = [];
        model.in = [];
        model.in2 = [];
        model.out = [1, 2, 3, 4, 5];
        model.out2 = [12, 12, 12, 12, 1];
        // model.label doubles as the on-diagram display text (Scicos
        // aliases it with graphics.id); category is derived separately by
        // get_block_type.sci via file-probe, so this is free to be the name.
        model.label = tag;
        x=standard_define([7.2 18],model,exprs,gr_i)
        x.graphics.in_label = [];
        x.graphics.out_label = ['data_i0', 'data_i1', 'data_q0', 'data_q1', 'sync'];
        x.graphics.style = 'shape=rectangle;fillColor=yellow';
        /* init exprs */
        x = init_exprs(x);
        debug_info('adc_mkid block loaded...')
    end
endfunction

function [x] = adc_mkid_update_ports(obj, bconfigfn)
    // fixed port count: only widths/labels change, no set_io() needed
    // (same approach as swreg_update_ports)
    x = obj;
    bconfig = fromJSON(bconfigfn, 'file');
    p = bconfig('parameters');
    graphics = x.graphics;
    model = x.model;
    model.in = [];
    model.in2 = [];
    model.out = [1, 2, 3, 4, 5];
    model.out2 = [12, 12, 12, 12, 1];
    graphics.in_label = [];
    graphics.out_label = ['data_i0', 'data_i1', 'data_q0', 'data_q1', 'sync'];
    graphics.style = 'shape=rectangle;fillColor=yellow';
    x.graphics = graphics;
    x.model = model;
endfunction
