// dac_mkid_4x: Xcos block definition, PyQt6-mask pattern.
// Generated by casper_xps/scripts/gen_sci_block.py -- review the port
// topology and TODOs below before relying on this in a real design.
function [x, y, typ] = dac_mkid_4x(job, arg1, arg2)
    x=[];y=[];typ=[];
    select job
    case 'set' then
        x = arg1;
        export_exprs_to_tmpdir(x);
        bconfig = run_mask(x);
        x = update_exprs_from_tmpdir(x);
        x = dac_mkid_4x_update_ports(x, bconfig);
    case 'define' then
        tag = 'dac_mkid_4x';
        model = scicos_model();
        model.sim = list(tag, 4);
        model.blocktype = 'c';
        model.rpar = [];
        exprs = [];
        gr_i = [];
        model.in = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13];
        model.in2 = [16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16];
        model.out = [];
        model.out2 = [];
        // model.label doubles as the on-diagram display text (Scicos
        // aliases it with graphics.id); category is derived separately by
        // get_block_type.sci via file-probe, so this is free to be the name.
        model.label = tag;
        x=standard_define([18 44.4],model,exprs,gr_i)
        x.graphics.in_label = ['data_i0', 'data_i1', 'data_i2', 'data_i3', 'data_q0', 'data_q1', 'data_q2', 'data_q3', 'sync_i', 'sync_q', 'sdenb', 'config10Data', 'reset'];
        x.graphics.out_label = [];
        x.graphics.style = 'shape=rectangle;fillColor=yellow';
        /* init exprs */
        x = init_exprs(x);
        debug_info('dac_mkid_4x block loaded...')
    end
endfunction

function [x] = dac_mkid_4x_update_ports(obj, bconfigfn)
    // fixed port count: only widths/labels change, no set_io() needed
    // (same approach as swreg_update_ports)
    x = obj;
    bconfig = fromJSON(bconfigfn, 'file');
    p = bconfig('parameters');
    graphics = x.graphics;
    model = x.model;
    model.in = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13];
    model.in2 = [16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16];
    model.out = [];
    model.out2 = [];
    graphics.in_label = ['data_i0', 'data_i1', 'data_i2', 'data_i3', 'data_q0', 'data_q1', 'data_q2', 'data_q3', 'sync_i', 'sync_q', 'sdenb', 'config10Data', 'reset'];
    graphics.out_label = [];
    graphics.style = 'shape=rectangle;fillColor=yellow';
    x.graphics = graphics;
    x.model = model;
endfunction
