// dram: Xcos block definition, PyQt6-mask pattern.
// Generated by casper_xps/scripts/gen_sci_block.py -- review the port
// topology and TODOs below before relying on this in a real design.
function [x, y, typ] = dram(job, arg1, arg2)
    x=[];y=[];typ=[];
    select job
    case 'set' then
        x = arg1;
        export_exprs_to_tmpdir(x);
        bconfig = run_mask(x);
        x = update_exprs_from_tmpdir(x);
        x = dram_update_ports(x, bconfig);
    case 'define' then
        tag = 'dram';
        model = scicos_model();
        model.sim = list(tag, 4);
        model.blocktype = 'c';
        model.rpar = [];
        exprs = [];
        gr_i = [];
        model.in = [1, 2, 3, 4, 5, 6, 7, 8];
        model.in2 = [1, 18, 32, 4, 1, 1, 1, 1];
        model.out = [1, 2, 3, 4, 5];
        model.out2 = [1, 32, 1, 1, 1];
        // model.label doubles as the on-diagram display text (Scicos
        // aliases it with graphics.id); category is derived separately by
        // get_block_type.sci via file-probe, so this is free to be the name.
        model.label = tag;
        x=standard_define([15.6 27.6],model,exprs,gr_i)
        x.graphics.in_label = ['rst', 'address', 'data_in', 'wr_be', 'RWn', 'cmd_tag', 'cmd_valid', 'rd_ack'];
        x.graphics.out_label = ['cmd_ack', 'data_out', 'rd_tag', 'rd_valid', 'phy_ready'];
        x.graphics.style = 'shape=rectangle;fillColor=yellow';
        /* init exprs */
        x = init_exprs(x);
        debug_info('dram block loaded...')
    end
endfunction

function [x] = dram_update_ports(obj, bconfigfn)
    // fixed port count: only widths/labels change, no set_io() needed
    // (same approach as swreg_update_ports)
    x = obj;
    bconfig = fromJSON(bconfigfn, 'file');
    p = bconfig('parameters');
    graphics = x.graphics;
    model = x.model;
    model.in = [1, 2, 3, 4, 5, 6, 7, 8];
    model.in2 = [1, strtod(p('ram_depth')), 32, 4, 1, 1, 1, 1];
    model.out = [1, 2, 3, 4, 5];
    model.out2 = [1, 32, 1, 1, 1];
    graphics.in_label = ['rst', 'address', 'data_in', 'wr_be', 'RWn', 'cmd_tag', 'cmd_valid', 'rd_ack'];
    graphics.out_label = ['cmd_ack', 'data_out', 'rd_tag', 'rd_valid', 'phy_ready'];
    graphics.style = 'shape=rectangle;fillColor=yellow';
    x.graphics = graphics;
    x.model = model;
endfunction
