// hmc: Xcos block definition, PyQt6-mask pattern.
// Generated by casper_xps/scripts/gen_sci_block.py -- review the port
// topology and TODOs below before relying on this in a real design.
function [x, y, typ] = hmc(job, arg1, arg2)
    x=[];y=[];typ=[];
    select job
    case 'set' then
        x = arg1;
        export_exprs_to_tmpdir(x);
        bconfig = run_mask(x);
        x = update_exprs_from_tmpdir(x);
        x = hmc_update_ports(x, bconfig);
    case 'define' then
        tag = 'hmc';
        model = scicos_model();
        model.sim = list(tag, 4);
        model.blocktype = 'c';
        model.rpar = [];
        exprs = [];
        gr_i = [];
        model.in = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];
        model.in2 = [1, 15, 256, 1, 15, 5, 1, 15, 256, 1, 15, 5];
        model.out = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11];
        model.out2 = [256, 1, 1, 1, 5, 256, 1, 1, 1, 5, 1];
        // model.label doubles as the on-diagram display text (Scicos
        // aliases it with graphics.id); category is derived separately by
        // get_block_type.sci via file-probe, so this is free to be the name.
        model.label = tag;
        x=standard_define([16.8 49.2],model,exprs,gr_i)
        x.graphics.in_label = ['wr_en_link2', 'wr_address_link2', 'data_in_link2', 'rd_en_link2', 'rd_address_link2', 'rd_tag_in_link2', 'wr_en_link3', 'wr_address_link3', 'data_in_link3', 'rd_en_link3', 'rd_address_link3', 'rd_tag_in_link3'];
        x.graphics.out_label = ['data_out_link2', 'data_valid_link2', 'wr_ready_link2', 'rd_ready_link2', 'rd_tag_out_link2', 'data_out_link3', 'data_valid_link3', 'wr_ready_link3', 'rd_ready_link3', 'rd_tag_out_link3', 'hmc_ok'];
        x = init_exprs(x);
        x.graphics.style = hmc_build_style(x.graphics.exprs(1));
        debug_info('hmc block loaded...')
    end
endfunction

/* build graphics.style for a given user-configurable block name, shown
   below the yellow fill. Strips ';' and '=' since those are mxGraph's
   own style-string delimiters -- an unescaped one would corrupt every
   key after it in the string, not just the label text. */
function [style] = hmc_build_style(name)
    name = strsubst(string(name), ';', '');
    name = strsubst(name, '=', '');
    style = 'shape=rectangle;fillColor=yellow;strokeColor=black;fontColor=black;fontSize=12;align=center;verticalAlign=top;verticalLabelPosition=bottom;noLabel=0;displayedLabel=' + name + ';whiteSpace=wrap;html=1;spacing=4;';
endfunction


function [x] = hmc_update_ports(obj, bconfigfn)
    // fixed port count: only widths/labels change, no set_io() needed
    // (same approach as swreg_update_ports)
    x = obj;
    bconfig = fromJSON(bconfigfn, 'file');
    p = bconfig('parameters');
    graphics = x.graphics;
    model = x.model;
    model.in = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];
    model.in2 = [1, strtod(p('sim_depth')), 256, 1, strtod(p('sim_depth')), 5, 1, strtod(p('sim_depth')), 256, 1, strtod(p('sim_depth')), 5];
    model.out = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11];
    model.out2 = [256, 1, 1, 1, 5, 256, 1, 1, 1, 5, 1];
    graphics.in_label = ['wr_en_link2', 'wr_address_link2', 'data_in_link2', 'rd_en_link2', 'rd_address_link2', 'rd_tag_in_link2', 'wr_en_link3', 'wr_address_link3', 'data_in_link3', 'rd_en_link3', 'rd_address_link3', 'rd_tag_in_link3'];
    graphics.out_label = ['data_out_link2', 'data_valid_link2', 'wr_ready_link2', 'rd_ready_link2', 'rd_tag_out_link2', 'data_out_link3', 'data_valid_link3', 'wr_ready_link3', 'rd_ready_link3', 'rd_tag_out_link3', 'hmc_ok'];
    graphics.style = hmc_build_style(p('name'));
    x.graphics = graphics;
    x.model = model;
endfunction
