// of_detect_bus: Xcos block definition, PyQt6-mask pattern.
// Generated by casper_xps/scripts/gen_sci_block.py -- review the port
// topology and TODOs below before relying on this in a real design.
function [x, y, typ] = of_detect_bus(job, arg1, arg2)
    x=[];y=[];typ=[];
    select job
    case 'set' then
        x = arg1;
        export_exprs_to_tmpdir(x);
        bconfig = run_mask(x);
        x = update_exprs_from_tmpdir(x);
        x = of_detect_bus_update_ports(x, bconfig);
    case 'define' then
        tag = 'of_detect_bus';
        model = scicos_model();
        model.sim = list(tag, 4);
        model.blocktype = 'c';
        model.rpar = [];
        exprs = [];
        gr_i = [];
        // matches of_detect_bus.json's own defaults (nStreams=8, bit_width=8)
        [iports_index, iports_label] = of_detect_bus_create_iports(8);
        model.in = iports_index;
        model.in2 = [8*ones(1, 8)];
        [oports_index, oports_label] = of_detect_bus_create_oports(8);
        model.out = oports_index;
        model.out2 = [1];
        // model.label doubles as the on-diagram display text (Scicos
        // aliases it with graphics.id); category is derived separately by
        // get_block_type.sci via file-probe, so this is free to be the name.
        model.label = tag;
        x=standard_define([9.6 16.8],model,exprs,gr_i)
        x.graphics.in_label = iports_label;
        x.graphics.out_label = oports_label;
        /* init exprs */
        x = init_exprs(x);
        x.graphics.style = of_detect_bus_build_style(x.graphics.exprs(1));
        debug_info('of_detect_bus block loaded...')
    end
endfunction

/* build the graphics.style string for a given user-configurable block
   name, showing it below the yellow fill (see displayedLabel). Strips
   ';' and '=' from the name since those are the mxGraph style string's
   own delimiter characters -- an unescaped one would corrupt every key
   after it in the style string, not just truncate the label. */
function [style] = of_detect_bus_build_style(name)
    name = strsubst(string(name), ';', '');
    name = strsubst(name, '=', '');
    style = 'shape=rectangle;fillColor=yellow;strokeColor=black;fontColor=black;fontSize=12;align=center;verticalAlign=top;verticalLabelPosition=bottom;noLabel=0;displayedLabel=' + name + ';whiteSpace=wrap;html=1;spacing=4;';
endfunction

function [ports_index, ports_label] = of_detect_bus_create_iports(factor)
    ports_label = [];
    ports_index = [];
    for i = 1:factor
        ports_label = [ports_label, 's' + string(i - 1)];
        ports_index = [ports_index, 0 + (i - 1) * 1 + 1];
    end
endfunction

function [ports_index, ports_label] = of_detect_bus_create_oports(factor)
    ports_label = ['overflow'];
    ports_index = [1];
endfunction

function [x] = of_detect_bus_update_ports(obj, bconfigfn)
    x = obj;
    bconfig = fromJSON(bconfigfn, 'file');
    p = bconfig('parameters');
    graphics = obj.graphics;
    exprs = graphics.exprs;
    model = obj.model;
    factor = strtod(p('nStreams'));
    evtin = [];
    evtout = [];
    [iports_index, iports_label] = of_detect_bus_create_iports(factor);
    [oports_index, oports_label] = of_detect_bus_create_oports(factor);
    // port I/O type: 1 = REAL (see set_io() docs); this mirrors wbfft/bus_expand,
    // which don't distinguish port datatypes any further
    io_in = [iports_index; iports_index];
    io_out = [oports_index; oports_index];
    io_in_type = ones(1, length(iports_index));
    io_out_type = ones(1, length(oports_index));
    [model, graphics, ok] = set_io(model, graphics, list(io_in', io_in_type), list(io_out', io_out_type), evtin, evtout);
    model.in = iports_index;
    model.in2 = [strtod(p('bit_width'))*ones(1, factor)];
    model.out = oports_index;
    model.out2 = [1];
    graphics.in_label = iports_label;
    graphics.out_label = oports_label;
    graphics.style = of_detect_bus_build_style(p('name'));
    graphics.exprs = exprs;
    x.graphics = graphics;
    x.model = model;
endfunction
