// qdr: Xcos block definition, PyQt6-mask pattern.
// Generated by casper_xps/scripts/gen_sci_block.py -- review the port
// topology and TODOs below before relying on this in a real design.
function [x, y, typ] = qdr(job, arg1, arg2)
    x=[];y=[];typ=[];
    select job
    case 'set' then
        x = arg1;
        export_exprs_to_tmpdir(x);
        bconfig = run_mask(x);
        x = update_exprs_from_tmpdir(x);
        x = qdr_update_ports(x, bconfig);
    case 'define' then
        tag = 'qdr';
        model = scicos_model();
        model.sim = list(tag, 4);
        model.blocktype = 'c';
        model.rpar = [];
        exprs = [];
        gr_i = [];
        model.in = [1, 2, 3, 4, 5];
        model.in2 = [1, 1, 8, 12, 72];
        model.out = [1, 2, 3, 4, 5];
        model.out2 = [72, 1, 1, 1, 1];
        // model.label doubles as the on-diagram display text (Scicos
        // aliases it with graphics.id); category is derived separately by
        // get_block_type.sci via file-probe, so this is free to be the name.
        model.label = tag;
        x=standard_define([12 20.4],model,exprs,gr_i)
        x.graphics.in_label = ['rd_en', 'wr_en', 'be', 'address', 'data_in'];
        x.graphics.out_label = ['data_out', 'data_valid', 'ack', 'phy_ready', 'cal_fail'];
        x = init_exprs(x);
        x.graphics.style = qdr_build_style(x.graphics.exprs(1));
        debug_info('qdr block loaded...')
    end
endfunction

/* build graphics.style for a given user-configurable block name, shown
   below the yellow fill. Strips ';' and '=' since those are mxGraph's
   own style-string delimiters -- an unescaped one would corrupt every
   key after it in the string, not just the label text. */
function [style] = qdr_build_style(name)
    name = strsubst(string(name), ';', '');
    name = strsubst(name, '=', '');
    style = 'shape=rectangle;fillColor=yellow;strokeColor=black;fontColor=black;fontSize=12;align=center;verticalAlign=top;verticalLabelPosition=bottom;noLabel=0;displayedLabel=' + name + ';whiteSpace=wrap;html=1;spacing=4;';
endfunction


function [x] = qdr_update_ports(obj, bconfigfn)
    // fixed port count: only widths/labels change, no set_io() needed
    // (same approach as swreg_update_ports)
    x = obj;
    bconfig = fromJSON(bconfigfn, 'file');
    p = bconfig('parameters');
    graphics = x.graphics;
    model = x.model;
    model.in = [1, 2, 3, 4, 5];
    model.in2 = [1, 1, 8, strtod(p('qdr_awidth')), 72];
    model.out = [1, 2, 3, 4, 5];
    model.out2 = [72, 1, 1, 1, 1];
    graphics.in_label = ['rd_en', 'wr_en', 'be', 'address', 'data_in'];
    graphics.out_label = ['data_out', 'data_valid', 'ack', 'phy_ready', 'cal_fail'];
    graphics.style = qdr_build_style(p('name'));
    x.graphics = graphics;
    x.model = model;
endfunction
