// quadc: Xcos block definition, PyQt6-mask pattern.
// Generated by casper_xps/scripts/gen_sci_block.py -- review the port
// topology and TODOs below before relying on this in a real design.
function [x, y, typ] = quadc(job, arg1, arg2)
    x=[];y=[];typ=[];
    select job
    case 'set' then
        x = arg1;
        export_exprs_to_tmpdir(x);
        bconfig = run_mask(x);
        x = update_exprs_from_tmpdir(x);
        x = quadc_update_ports(x, bconfig);
    case 'define' then
        tag = 'quadc';
        model = scicos_model();
        model.sim = list(tag, 4);
        model.blocktype = 'c';
        model.rpar = [];
        exprs = [];
        gr_i = [];
        model.in = [1, 2, 3, 4, 5, 6];
        model.in2 = [8, 8, 8, 8, 1, 1];
        model.out = [1, 2, 3, 4, 5, 6];
        model.out2 = [8, 8, 8, 8, 1, 1];
        // model.label doubles as the on-diagram display text (Scicos
        // aliases it with graphics.id); category is derived separately by
        // get_block_type.sci via file-probe, so this is free to be the name.
        model.label = tag;
        x=standard_define([9.6 19.2],model,exprs,gr_i)
        x.graphics.in_label = ['sim_adc0', 'sim_adc1', 'sim_adc2', 'sim_adc3', 'sim_valid', 'sim_sync'];
        x.graphics.out_label = ['data0', 'data1', 'data2', 'data3', 'valid', 'sync'];
        x.graphics.style = 'shape=rectangle;fillColor=yellow';
        /* init exprs */
        x = init_exprs(x);
        debug_info('quadc block loaded...')
    end
endfunction

function [x] = quadc_update_ports(obj, bconfigfn)
    // fixed port count: only widths/labels change, no set_io() needed
    // (same approach as swreg_update_ports)
    x = obj;
    bconfig = fromJSON(bconfigfn, 'file');
    p = bconfig('parameters');
    graphics = x.graphics;
    model = x.model;
    model.in = [1, 2, 3, 4, 5, 6];
    model.in2 = [8, 8, 8, 8, 1, 1];
    model.out = [1, 2, 3, 4, 5, 6];
    model.out2 = [8, 8, 8, 8, 1, 1];
    graphics.in_label = ['sim_adc0', 'sim_adc1', 'sim_adc2', 'sim_adc3', 'sim_valid', 'sim_sync'];
    graphics.out_label = ['data0', 'data1', 'data2', 'data3', 'valid', 'sync'];
    graphics.style = 'shape=rectangle;fillColor=yellow';
    x.graphics = graphics;
    x.model = model;
endfunction
