// red_pitaya_dac: Xcos block definition, PyQt6-mask pattern.
// Generated by casper_xps/scripts/gen_sci_block.py -- review the port
// topology and TODOs below before relying on this in a real design.
function [x, y, typ] = red_pitaya_dac(job, arg1, arg2)
    x=[];y=[];typ=[];
    select job
    case 'set' then
        x = arg1;
        export_exprs_to_tmpdir(x);
        bconfig = run_mask(x);
        x = update_exprs_from_tmpdir(x);
        x = red_pitaya_dac_update_ports(x, bconfig);
    case 'define' then
        tag = 'red_pitaya_dac';
        model = scicos_model();
        model.sim = list(tag, 4);
        model.blocktype = 'c';
        model.rpar = [];
        exprs = [];
        gr_i = [];
        model.in = [1, 2, 3, 4];
        model.in2 = [16, 16, 10, 10];
        model.out = [];
        model.out2 = [];
        // model.label doubles as the on-diagram display text (Scicos
        // aliases it with graphics.id); category is derived separately by
        // get_block_type.sci via file-probe, so this is free to be the name.
        model.label = tag;
        x=standard_define([16.8 31.2],model,exprs,gr_i)
        x.graphics.in_label = ['dac_reset_in', 'dac_data_valid_in', 'dac0_data_i_in', 'dac1_data_q_in'];
        x.graphics.out_label = [];
        x.graphics.style = 'shape=rectangle;fillColor=yellow';
        /* init exprs */
        x = init_exprs(x);
        debug_info('red_pitaya_dac block loaded...')
    end
endfunction

function [x] = red_pitaya_dac_update_ports(obj, bconfigfn)
    // fixed port count: only widths/labels change, no set_io() needed
    // (same approach as swreg_update_ports)
    x = obj;
    bconfig = fromJSON(bconfigfn, 'file');
    p = bconfig('parameters');
    graphics = x.graphics;
    model = x.model;
    model.in = [1, 2, 3, 4];
    model.in2 = [16, 16, strtod(p('bits')), strtod(p('bits'))];
    model.out = [];
    model.out2 = [];
    graphics.in_label = ['dac_reset_in', 'dac_data_valid_in', 'dac0_data_i_in', 'dac1_data_q_in'];
    graphics.out_label = [];
    graphics.style = 'shape=rectangle;fillColor=yellow';
    x.graphics = graphics;
    x.model = model;
endfunction
