// skarab_adc4x3g_14: Xcos block definition, PyQt6-mask pattern.
// Generated by casper_xps/scripts/gen_sci_block.py -- review the port
// topology and TODOs below before relying on this in a real design.
function [x, y, typ] = skarab_adc4x3g_14(job, arg1, arg2)
    x=[];y=[];typ=[];
    select job
    case 'set' then
        x = arg1;
        export_exprs_to_tmpdir(x);
        bconfig = run_mask(x);
        x = update_exprs_from_tmpdir(x);
        x = skarab_adc4x3g_14_update_ports(x, bconfig);
    case 'define' then
        tag = 'skarab_adc4x3g_14';
        model = scicos_model();
        model.sim = list(tag, 4);
        model.blocktype = 'c';
        model.rpar = [];
        exprs = [];
        gr_i = [];
        model.in = [];
        model.in2 = [];
        model.out = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36];
        model.out2 = [1, 1, 1, 1, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14];
        // model.label doubles as the on-diagram display text (Scicos
        // aliases it with graphics.id); category is derived separately by
        // get_block_type.sci via file-probe, so this is free to be the name.
        model.label = tag;
        x=standard_define([26.4 60],model,exprs,gr_i)
        x.graphics.in_label = [];
        x.graphics.out_label = ['adc0_data_val_out', 'adc1_data_val_out', 'adc2_data_val_out', 'adc3_data_val_out', 'adc0_data_q_out0', 'adc0_data_i_out0', 'adc0_data_q_out1', 'adc0_data_i_out1', 'adc0_data_q_out2', 'adc0_data_i_out2', 'adc0_data_q_out3', 'adc0_data_i_out3', 'adc1_data_q_out0', 'adc1_data_i_out0', 'adc1_data_q_out1', 'adc1_data_i_out1', 'adc1_data_q_out2', 'adc1_data_i_out2', 'adc1_data_q_out3', 'adc1_data_i_out3', 'adc2_data_q_out0', 'adc2_data_i_out0', 'adc2_data_q_out1', 'adc2_data_i_out1', 'adc2_data_q_out2', 'adc2_data_i_out2', 'adc2_data_q_out3', 'adc2_data_i_out3', 'adc3_data_q_out0', 'adc3_data_i_out0', 'adc3_data_q_out1', 'adc3_data_i_out1', 'adc3_data_q_out2', 'adc3_data_i_out2', 'adc3_data_q_out3', 'adc3_data_i_out3'];
        x.graphics.style = 'shape=rectangle;fillColor=yellow';
        /* init exprs */
        x = init_exprs(x);
        debug_info('skarab_adc4x3g_14 block loaded...')
    end
endfunction

function [x] = skarab_adc4x3g_14_update_ports(obj, bconfigfn)
    // fixed port count: only widths/labels change, no set_io() needed
    // (same approach as swreg_update_ports)
    x = obj;
    bconfig = fromJSON(bconfigfn, 'file');
    p = bconfig('parameters');
    graphics = x.graphics;
    model = x.model;
    model.in = [];
    model.in2 = [];
    model.out = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36];
    model.out2 = [1, 1, 1, 1, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14];
    graphics.in_label = [];
    graphics.out_label = ['adc0_data_val_out', 'adc1_data_val_out', 'adc2_data_val_out', 'adc3_data_val_out', 'adc0_data_q_out0', 'adc0_data_i_out0', 'adc0_data_q_out1', 'adc0_data_i_out1', 'adc0_data_q_out2', 'adc0_data_i_out2', 'adc0_data_q_out3', 'adc0_data_i_out3', 'adc1_data_q_out0', 'adc1_data_i_out0', 'adc1_data_q_out1', 'adc1_data_i_out1', 'adc1_data_q_out2', 'adc1_data_i_out2', 'adc1_data_q_out3', 'adc1_data_i_out3', 'adc2_data_q_out0', 'adc2_data_i_out0', 'adc2_data_q_out1', 'adc2_data_i_out1', 'adc2_data_q_out2', 'adc2_data_i_out2', 'adc2_data_q_out3', 'adc2_data_i_out3', 'adc3_data_q_out0', 'adc3_data_i_out0', 'adc3_data_q_out1', 'adc3_data_i_out1', 'adc3_data_q_out2', 'adc3_data_i_out2', 'adc3_data_q_out3', 'adc3_data_i_out3'];
    graphics.style = 'shape=rectangle;fillColor=yellow';
    x.graphics = graphics;
    x.model = model;
endfunction
