// vla_dts: Xcos block definition, PyQt6-mask pattern.
// Generated by casper_xps/scripts/gen_sci_block.py -- review the port
// topology and TODOs below before relying on this in a real design.
function [x, y, typ] = vla_dts(job, arg1, arg2)
    x=[];y=[];typ=[];
    select job
    case 'set' then
        x = arg1;
        export_exprs_to_tmpdir(x);
        bconfig = run_mask(x);
        x = update_exprs_from_tmpdir(x);
        x = vla_dts_update_ports(x, bconfig);
    case 'define' then
        tag = 'vla_dts';
        model = scicos_model();
        model.sim = list(tag, 4);
        model.blocktype = 'c';
        model.rpar = [];
        exprs = [];
        gr_i = [];
        model.in = [];
        model.in2 = [];
        model.out = [1, 2, 3];
        model.out2 = [64, 1, 1];
        // model.label doubles as the on-diagram display text (Scicos
        // aliases it with graphics.id); category is derived separately by
        // get_block_type.sci via file-probe, so this is free to be the name.
        model.label = tag;
        x=standard_define([13 28],model,exprs,gr_i)
        x.graphics.in_label = [];
        x.graphics.out_label = ['data_out', 'valid', 'sync'];
        x.graphics.style = 'shape=rectangle;fillColor=yellow';
        /* init exprs */
        x = init_exprs(x);
        debug_info('vla_dts block loaded...')
    end
endfunction

function [x] = vla_dts_update_ports(obj, bconfigfn)
    // fixed port count: only widths/labels change, no set_io() needed
    // (same approach as swreg_update_ports)
    x = obj;
    bconfig = fromJSON(bconfigfn, 'file');
    p = bconfig('parameters');
    graphics = x.graphics;
    model = x.model;
    model.in = [];
    model.in2 = [];
    model.out = [1, 2, 3];
    model.out2 = [strtod(p('data_width')), 1, 1];
    graphics.in_label = [];
    graphics.out_label = ['data_out', 'valid', 'sync'];
    graphics.style = 'shape=rectangle;fillColor=yellow';
    x.graphics = graphics;
    x.model = model;
endfunction
