# Form implementation for the Bus Delay mask dialog.
# Hand-generated by casper_dsp/scripts/gen_block_gui.py to match the layout
# in ui/bus_delay.ui -- if PyQt6/pyuic6 is available, regenerate with:
#   pyuic6 ui/bus_delay.ui -o bus_delay_ui.py
# and keep both in sync by hand otherwise.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(560, 440)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)

        self.desc_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.desc_label.setWordWrap(True)
        self.desc_label.setObjectName("desc_label")
        self.verticalLayout.addWidget(self.desc_label)

        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.label_n_bits = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_n_bits.setObjectName("label_n_bits")
        self.gridLayout.addWidget(self.label_n_bits, 1, 0, 1, 1)
        self.n_bits = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.n_bits.setObjectName("n_bits")
        self.gridLayout.addWidget(self.n_bits, 1, 1, 1, 2)
        self.label_csp_latency = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_csp_latency.setObjectName("label_csp_latency")
        self.gridLayout.addWidget(self.label_csp_latency, 2, 0, 1, 1)
        self.csp_latency = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.csp_latency.setObjectName("csp_latency")
        self.gridLayout.addWidget(self.csp_latency, 2, 1, 1, 2)
        self.label_cmplx = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_cmplx.setObjectName("label_cmplx")
        self.gridLayout.addWidget(self.label_cmplx, 3, 0, 1, 1)
        self.cmplx = QtWidgets.QCheckBox(parent=self.scrollAreaWidgetContents)
        self.cmplx.setObjectName("cmplx")
        self.gridLayout.addWidget(self.cmplx, 3, 1, 1, 2)
        self.label_enable = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_enable.setObjectName("label_enable")
        self.gridLayout.addWidget(self.label_enable, 4, 0, 1, 1)
        self.enable = QtWidgets.QCheckBox(parent=self.scrollAreaWidgetContents)
        self.enable.setObjectName("enable")
        self.gridLayout.addWidget(self.enable, 4, 1, 1, 2)
        self.label_reg_retiming = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_reg_retiming.setObjectName("label_reg_retiming")
        self.gridLayout.addWidget(self.label_reg_retiming, 5, 0, 1, 1)
        self.reg_retiming = QtWidgets.QCheckBox(parent=self.scrollAreaWidgetContents)
        self.reg_retiming.setObjectName("reg_retiming")
        self.gridLayout.addWidget(self.reg_retiming, 5, 1, 1, 2)
        self.label_misc = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_misc.setObjectName("label_misc")
        self.gridLayout.addWidget(self.label_misc, 6, 0, 1, 1)
        self.misc = QtWidgets.QCheckBox(parent=self.scrollAreaWidgetContents)
        self.misc.setObjectName("misc")
        self.gridLayout.addWidget(self.misc, 6, 1, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.buttonLayout.addItem(spacerItem)
        self.button_apply = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_apply.setObjectName("button_apply")
        self.buttonLayout.addWidget(self.button_apply)
        self.button_ok = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_ok.setObjectName("button_ok")
        self.buttonLayout.addWidget(self.button_ok)
        self.button_cancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_cancel.setObjectName("button_cancel")
        self.buttonLayout.addWidget(self.button_cancel)
        self.verticalLayout.addLayout(self.buttonLayout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bus Delay"))
        self.title_label.setText(_translate("MainWindow", "Bus Delay"))
        self.desc_label.setText(_translate("MainWindow", "Delay components of a bus"))
        self.label_n_bits.setText(_translate("MainWindow", "input bit widths"))
        self.label_csp_latency.setText(_translate("MainWindow", "latency"))
        self.label_cmplx.setText(_translate("MainWindow", "complex data"))
        self.label_enable.setText(_translate("MainWindow", "enable port"))
        self.label_reg_retiming.setText(_translate("MainWindow", "implement using behavioral HDL"))
        self.label_misc.setText(_translate("MainWindow", "misc support"))
        self.button_apply.setText(_translate("MainWindow", "Apply"))
        self.button_ok.setText(_translate("MainWindow", "OK"))
        self.button_cancel.setText(_translate("MainWindow", "Cancel"))
