# Form implementation for the Triggered Counter mask dialog.
# Hand-generated by casper_dsp/scripts/gen_block_gui.py to match the layout
# in ui/triggered_counter.ui -- if PyQt6/pyuic6 is available, regenerate with:
#   pyuic6 ui/triggered_counter.ui -o triggered_counter_ui.py
# and keep both in sync by hand otherwise.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(741, 280)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)

        self.desc_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.desc_label.setWordWrap(True)
        self.desc_label.setObjectName("desc_label")
        self.verticalLayout.addWidget(self.desc_label)

        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout.setColumnStretch(1, 1)
        self.label_len = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_len.setObjectName("label_len")
        self.label_len.setWordWrap(True)
        self.label_len.setFixedWidth(451)
        self.gridLayout.addWidget(self.label_len, 1, 0, 1, 1)
        self.len = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.len.setObjectName("len")
        self.len.setRange(1, 100000000)
        self.gridLayout.addWidget(self.len, 1, 1, 1, 2)
        self.label_count_width = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_count_width.setObjectName("label_count_width")
        self.label_count_width.setWordWrap(True)
        self.label_count_width.setFixedWidth(451)
        self.gridLayout.addWidget(self.label_count_width, 2, 0, 1, 1)
        self.count_width = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.count_width.setObjectName("count_width")
        self.count_width.setRange(1, 64)
        self.gridLayout.addWidget(self.count_width, 2, 1, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.buttonLayout.addItem(spacerItem)
        self.button_apply = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_apply.setObjectName("button_apply")
        self.buttonLayout.addWidget(self.button_apply)
        self.button_ok = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_ok.setObjectName("button_ok")
        self.buttonLayout.addWidget(self.button_ok)
        self.button_cancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_cancel.setObjectName("button_cancel")
        self.buttonLayout.addWidget(self.button_cancel)
        self.verticalLayout.addLayout(self.buttonLayout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Triggered Counter"))
        self.title_label.setText(_translate("MainWindow", "Triggered Counter"))
        self.desc_label.setText(_translate("MainWindow", "Counts clocks after being triggered, up to a run length. count_width is added here (not a casper_library mask param) for the Xcos port's explicit output width."))
        self.label_len.setText(_translate("MainWindow", "Run Length"))
        self.label_count_width.setText(_translate("MainWindow", "Count Width (added for Xcos; not a casper_library mask param)"))
        self.button_apply.setText(_translate("MainWindow", "Apply"))
        self.button_ok.setText(_translate("MainWindow", "OK"))
        self.button_cancel.setText(_translate("MainWindow", "Cancel"))
