# Form implementation for the Exception Constraint mask dialog.
# Hand-generated by casper_xps/scripts/gen_block_gui.py to match the layout
# in ui/exception_constraint.ui -- if PyQt6/pyuic6 is available, regenerate with:
#   pyuic6 ui/exception_constraint.ui -o exception_constraint_ui.py
# and keep both in sync by hand otherwise.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(578, 310)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)

        self.desc_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.desc_label.setWordWrap(True)
        self.desc_label.setObjectName("desc_label")
        self.verticalLayout.addWidget(self.desc_label)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout.setColumnStretch(1, 1)
        self.label_name = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_name.setObjectName("label_name")
        self.label_name.setWordWrap(True)
        self.label_name.setFixedWidth(178)
        self.gridLayout.addWidget(self.label_name, 1, 0, 1, 1)
        self.name = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 1, 1, 1, 2)
        self.label_constraint_type = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_constraint_type.setObjectName("label_constraint_type")
        self.label_constraint_type.setWordWrap(True)
        self.label_constraint_type.setFixedWidth(178)
        self.gridLayout.addWidget(self.label_constraint_type, 2, 0, 1, 1)
        self.constraint_type = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.constraint_type.setObjectName("constraint_type")
        self.constraint_type.addItem("")
        self.constraint_type.addItem("")
        self.gridLayout.addWidget(self.constraint_type, 2, 1, 1, 2)
        self.label_num_clock_cycles = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_num_clock_cycles.setObjectName("label_num_clock_cycles")
        self.label_num_clock_cycles.setWordWrap(True)
        self.label_num_clock_cycles.setFixedWidth(178)
        self.gridLayout.addWidget(self.label_num_clock_cycles, 3, 0, 1, 1)
        self.num_clock_cycles = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.num_clock_cycles.setObjectName("num_clock_cycles")
        self.gridLayout.addWidget(self.num_clock_cycles, 3, 1, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.buttonLayout.addItem(spacerItem)
        self.button_apply = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_apply.setObjectName("button_apply")
        self.buttonLayout.addWidget(self.button_apply)
        self.button_ok = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_ok.setObjectName("button_ok")
        self.buttonLayout.addWidget(self.button_ok)
        self.button_cancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_cancel.setObjectName("button_cancel")
        self.buttonLayout.addWidget(self.button_cancel)
        self.verticalLayout.addLayout(self.buttonLayout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Exception Constraint"))
        self.title_label.setText(_translate("MainWindow", "Exception Constraint"))
        self.desc_label.setText(_translate("MainWindow", "Yellow Block utility to add to a signal path to be marked with a False Path or Multicycle constraint."))
        self.label_name.setText(_translate("MainWindow", "Block name"))
        self.name.setToolTip(_translate("MainWindow", "A name you choose for this block instance, e.g. to note what it's used for in this design. Shown below the block on the diagram."))
        self.label_constraint_type.setText(_translate("MainWindow", "Constraint Type"))
        self.constraint_type.setItemText(0, _translate("MainWindow", "False Path Constraint"))
        self.constraint_type.setItemText(1, _translate("MainWindow", "Multicycle Constraint"))
        self.label_num_clock_cycles.setText(_translate("MainWindow", "Number of Clock Cycles"))
        self.button_apply.setText(_translate("MainWindow", "Apply"))
        self.button_ok.setText(_translate("MainWindow", "OK"))
        self.button_cancel.setText(_translate("MainWindow", "Cancel"))
