# Form implementation for the 1-Cycle Overflow Detector mask dialog.
# Hand-generated by casper_dsp/scripts/gen_block_gui.py to match the layout
# in ui/of1.ui -- if PyQt6/pyuic6 is available, regenerate with:
#   pyuic6 ui/of1.ui -o of1_ui.py
# and keep both in sync by hand otherwise.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(566, 280)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)

        self.desc_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.desc_label.setWordWrap(True)
        self.desc_label.setObjectName("desc_label")
        self.verticalLayout.addWidget(self.desc_label)

        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout.setColumnStretch(1, 1)
        self.label_bit_num = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_bit_num.setObjectName("label_bit_num")
        self.label_bit_num.setWordWrap(True)
        self.label_bit_num.setMaximumWidth(276)
        self.gridLayout.addWidget(self.label_bit_num, 1, 0, 1, 1)
        self.bit_num = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.bit_num.setObjectName("bit_num")
        self.bit_num.setRange(0, 127)
        self.gridLayout.addWidget(self.bit_num, 1, 1, 1, 2)
        self.label_n_adc_bits = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_n_adc_bits.setObjectName("label_n_adc_bits")
        self.label_n_adc_bits.setWordWrap(True)
        self.label_n_adc_bits.setMaximumWidth(276)
        self.gridLayout.addWidget(self.label_n_adc_bits, 2, 0, 1, 1)
        self.n_adc_bits = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.n_adc_bits.setObjectName("n_adc_bits")
        self.n_adc_bits.setRange(1, 128)
        self.gridLayout.addWidget(self.n_adc_bits, 2, 1, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.buttonLayout.addItem(spacerItem)
        self.button_apply = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_apply.setObjectName("button_apply")
        self.buttonLayout.addWidget(self.button_apply)
        self.button_ok = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_ok.setObjectName("button_ok")
        self.buttonLayout.addWidget(self.button_ok)
        self.button_cancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_cancel.setObjectName("button_cancel")
        self.buttonLayout.addWidget(self.button_cancel)
        self.verticalLayout.addLayout(self.buttonLayout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "1-Cycle Overflow Detector"))
        self.title_label.setText(_translate("MainWindow", "1-Cycle Overflow Detector"))
        self.desc_label.setText(_translate("MainWindow", "1-cycle overflow detector for an n-bit ADC output (simulation only)."))
        self.label_bit_num.setText(_translate("MainWindow", "Bit index of overflow detection bus:"))
        self.label_n_adc_bits.setText(_translate("MainWindow", "Number of bits in ADC"))
        self.button_apply.setText(_translate("MainWindow", "Apply"))
        self.button_ok.setText(_translate("MainWindow", "OK"))
        self.button_cancel.setText(_translate("MainWindow", "Cancel"))
