# Form implementation for the Spectrum Power mask dialog.
# Hand-generated by casper_dsp/scripts/gen_block_gui.py to match the layout
# in ui/spect_power.ui -- if PyQt6/pyuic6 is available, regenerate with:
#   pyuic6 ui/spect_power.ui -o spect_power_ui.py
# and keep both in sync by hand otherwise.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(560, 400)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)

        self.desc_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.desc_label.setWordWrap(True)
        self.desc_label.setObjectName("desc_label")
        self.verticalLayout.addWidget(self.desc_label)

        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.label_bitwidth = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_bitwidth.setObjectName("label_bitwidth")
        self.gridLayout.addWidget(self.label_bitwidth, 1, 0, 1, 1)
        self.bitwidth = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.bitwidth.setObjectName("bitwidth")
        self.bitwidth.setRange(1, 128)
        self.gridLayout.addWidget(self.bitwidth, 1, 1, 1, 2)
        self.label_add_latency = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_add_latency.setObjectName("label_add_latency")
        self.gridLayout.addWidget(self.label_add_latency, 2, 0, 1, 1)
        self.add_latency = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.add_latency.setObjectName("add_latency")
        self.add_latency.setRange(0, 32)
        self.gridLayout.addWidget(self.add_latency, 2, 1, 1, 2)
        self.label_mult_latency = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_mult_latency.setObjectName("label_mult_latency")
        self.gridLayout.addWidget(self.label_mult_latency, 3, 0, 1, 1)
        self.mult_latency = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.mult_latency.setObjectName("mult_latency")
        self.mult_latency.setRange(0, 32)
        self.gridLayout.addWidget(self.mult_latency, 3, 1, 1, 2)
        self.label_mode = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_mode.setObjectName("label_mode")
        self.gridLayout.addWidget(self.label_mode, 4, 0, 1, 1)
        self.mode = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.mode.setObjectName("mode")
        self.mode.addItem("")
        self.mode.addItem("")
        self.gridLayout.addWidget(self.mode, 4, 1, 1, 2)
        self.label_n_inputs = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_n_inputs.setObjectName("label_n_inputs")
        self.gridLayout.addWidget(self.label_n_inputs, 5, 0, 1, 1)
        self.n_inputs = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.n_inputs.setObjectName("n_inputs")
        self.n_inputs.setRange(1, 64)
        self.gridLayout.addWidget(self.n_inputs, 5, 1, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.buttonLayout.addItem(spacerItem)
        self.button_apply = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_apply.setObjectName("button_apply")
        self.buttonLayout.addWidget(self.button_apply)
        self.button_ok = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_ok.setObjectName("button_ok")
        self.buttonLayout.addWidget(self.button_ok)
        self.button_cancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_cancel.setObjectName("button_cancel")
        self.buttonLayout.addWidget(self.button_cancel)
        self.verticalLayout.addLayout(self.buttonLayout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Spectrum Power"))
        self.title_label.setText(_translate("MainWindow", "Spectrum Power"))
        self.desc_label.setText(_translate("MainWindow", "Computes power (|re|^2+|im|^2) for n_inputs simultaneous complex spectral streams."))
        self.label_bitwidth.setText(_translate("MainWindow", "Bit Width"))
        self.label_add_latency.setText(_translate("MainWindow", "Adder Latency"))
        self.label_mult_latency.setText(_translate("MainWindow", "Mult Latency"))
        self.label_mode.setText(_translate("MainWindow", "Mode"))
        self.mode.setItemText(0, _translate("MainWindow", "accumulate"))
        self.mode.setItemText(1, _translate("MainWindow", "single shot"))
        self.label_n_inputs.setText(_translate("MainWindow", "Number of Inputs"))
        self.button_apply.setText(_translate("MainWindow", "Apply"))
        self.button_ok.setText(_translate("MainWindow", "OK"))
        self.button_cancel.setText(_translate("MainWindow", "Cancel"))
