# Form implementation generated from reading ui file 'ui/sw_reg.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(520, 560)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 500, 520))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")

        # ---- title ----
        self.label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)

        # ---- header frame ----
        self.frame = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 3)

        # ---- description ----
        self.label_3 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 3)

        # ---- parameter frame ----
        self.frame_3 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setObjectName("gridLayout_2")

        self.label_4 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.io_dir = QtWidgets.QComboBox(parent=self.frame_3)
        self.io_dir.setObjectName("io_dir")
        self.io_dir.addItem("")
        self.io_dir.addItem("")
        self.gridLayout_2.addWidget(self.io_dir, 0, 1, 1, 1)

        self.label_5 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.mode = QtWidgets.QComboBox(parent=self.frame_3)
        self.mode.setObjectName("mode")
        self.mode.addItem("")
        self.mode.addItem("")
        self.mode.addItem("")
        self.gridLayout_2.addWidget(self.mode, 1, 1, 1, 1)

        self.label_6 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.names = QtWidgets.QLineEdit(parent=self.frame_3)
        self.names.setObjectName("names")
        self.gridLayout_2.addWidget(self.names, 2, 1, 1, 2)

        self.label_7 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 1)
        self.bitwidths = QtWidgets.QLineEdit(parent=self.frame_3)
        self.bitwidths.setObjectName("bitwidths")
        self.gridLayout_2.addWidget(self.bitwidths, 3, 1, 1, 2)

        self.label_8 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 4, 0, 1, 1)
        self.bin_pts = QtWidgets.QLineEdit(parent=self.frame_3)
        self.bin_pts.setObjectName("bin_pts")
        self.gridLayout_2.addWidget(self.bin_pts, 4, 1, 1, 2)

        self.label_9 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 5, 0, 1, 1)
        self.arith_types = QtWidgets.QLineEdit(parent=self.frame_3)
        self.arith_types.setObjectName("arith_types")
        self.gridLayout_2.addWidget(self.arith_types, 5, 1, 1, 2)

        self.label_10 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 6, 0, 1, 1)
        self.io_delay = QtWidgets.QSpinBox(parent=self.frame_3)
        self.io_delay.setMinimum(0)
        self.io_delay.setMaximum(64)
        self.io_delay.setProperty("value", 1)
        self.io_delay.setObjectName("io_delay")
        self.gridLayout_2.addWidget(self.io_delay, 6, 1, 1, 1)

        self.label_11 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 7, 0, 1, 1)
        self.sample_period = QtWidgets.QSpinBox(parent=self.frame_3)
        self.sample_period.setMinimum(1)
        self.sample_period.setMaximum(1024)
        self.sample_period.setProperty("value", 1)
        self.sample_period.setObjectName("sample_period")
        self.gridLayout_2.addWidget(self.sample_period, 7, 1, 1, 1)

        self.sim_port = QtWidgets.QCheckBox(parent=self.frame_3)
        self.sim_port.setChecked(True)
        self.sim_port.setObjectName("sim_port")
        self.gridLayout_2.addWidget(self.sim_port, 8, 0, 1, 2)

        self.show_format = QtWidgets.QCheckBox(parent=self.frame_3)
        self.show_format.setChecked(True)
        self.show_format.setObjectName("show_format")
        self.gridLayout_2.addWidget(self.show_format, 9, 0, 1, 2)

        self.gridLayout.addWidget(self.frame_3, 3, 0, 1, 3)

        # ---- buttons ----
        self.button_ok = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.button_ok.setObjectName("button_ok")
        self.gridLayout.addWidget(self.button_ok, 4, 0, 1, 1)
        self.button_cancel = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.button_cancel.setObjectName("button_cancel")
        self.gridLayout.addWidget(self.button_cancel, 4, 1, 1, 1)
        self.button_apply = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.button_apply.setObjectName("button_apply")
        self.gridLayout.addWidget(self.button_apply, 4, 2, 1, 1)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.io_dir.setCurrentIndex(0)
        self.mode.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Software Register"))
        self.label.setText(_translate("MainWindow", "Software Register Block (mask)"))
        self.label_2.setText(_translate("MainWindow", "CASPER Software Register"))
        self.label_3.setText(_translate("MainWindow", "Defines a 32-bit software register used to pass "
                                                        "arbitrary bit-fields between the FPGA fabric and "
                                                        "the embedded/host processor."))
        self.label_4.setText(_translate("MainWindow", "Direction (io_dir)"))
        self.io_dir.setItemText(0, _translate("MainWindow", "From Processor"))
        self.io_dir.setItemText(1, _translate("MainWindow", "To Processor"))
        self.label_5.setText(_translate("MainWindow", "Mode"))
        self.mode.setItemText(0, _translate("MainWindow", "one value"))
        self.mode.setItemText(1, _translate("MainWindow", "fields of equal size"))
        self.mode.setItemText(2, _translate("MainWindow", "fields of arbitrary size"))
        self.label_6.setText(_translate("MainWindow", "Names [msb...lsb]"))
        self.names.setText(_translate("MainWindow", "['reg']"))
        self.label_7.setText(_translate("MainWindow", "Bitwidths [msb...lsb]"))
        self.bitwidths.setText(_translate("MainWindow", "[32]"))
        self.label_8.setText(_translate("MainWindow", "Binary points [msb...lsb]"))
        self.bin_pts.setText(_translate("MainWindow", "[0]"))
        self.label_9.setText(_translate("MainWindow", "Data types [msb...lsb] (0=ufix,1=fix,2=bool)"))
        self.arith_types.setText(_translate("MainWindow", "[0]"))
        self.label_10.setText(_translate("MainWindow", "IO delay (io_delay)"))
        self.label_11.setText(_translate("MainWindow", "Sample period (sample_period)"))
        self.sim_port.setText(_translate("MainWindow", "Add simulation-only ports (sim_port)"))
        self.show_format.setText(_translate("MainWindow", "Show format string on icon (show_format)"))
        self.button_ok.setText(_translate("MainWindow", "OK"))
        self.button_cancel.setText(_translate("MainWindow", "Cancel"))
        self.button_apply.setText(_translate("MainWindow", "Apply"))
