# Form implementation for the Revision Control System mask dialog.
# Hand-generated by casper_dsp/scripts/gen_block_gui.py to match the layout
# in ui/rcs.ui -- if PyQt6/pyuic6 is available, regenerate with:
#   pyuic6 ui/rcs.ui -o rcs_ui.py
# and keep both in sync by hand otherwise.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(711, 320)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)

        self.desc_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.desc_label.setWordWrap(True)
        self.desc_label.setObjectName("desc_label")
        self.verticalLayout.addWidget(self.desc_label)

        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout.setColumnStretch(1, 1)
        self.label_app_src = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_app_src.setObjectName("label_app_src")
        self.label_app_src.setWordWrap(True)
        self.label_app_src.setFixedWidth(311)
        self.gridLayout.addWidget(self.label_app_src, 1, 0, 1, 1)
        self.app_src = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.app_src.setObjectName("app_src")
        self.app_src.addItem("")
        self.app_src.addItem("")
        self.app_src.addItem("")
        self.gridLayout.addWidget(self.app_src, 1, 1, 1, 2)
        self.label_lib_src = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_lib_src.setObjectName("label_lib_src")
        self.label_lib_src.setWordWrap(True)
        self.label_lib_src.setFixedWidth(311)
        self.gridLayout.addWidget(self.label_lib_src, 2, 0, 1, 1)
        self.lib_src = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.lib_src.setObjectName("lib_src")
        self.lib_src.addItem("")
        self.lib_src.addItem("")
        self.lib_src.addItem("")
        self.gridLayout.addWidget(self.lib_src, 2, 1, 1, 2)
        self.label_user_val = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_user_val.setObjectName("label_user_val")
        self.label_user_val.setWordWrap(True)
        self.label_user_val.setFixedWidth(311)
        self.gridLayout.addWidget(self.label_user_val, 3, 0, 1, 1)
        self.user_val = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.user_val.setObjectName("user_val")
        self.gridLayout.addWidget(self.user_val, 3, 1, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.buttonLayout.addItem(spacerItem)
        self.button_apply = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_apply.setObjectName("button_apply")
        self.buttonLayout.addWidget(self.button_apply)
        self.button_ok = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_ok.setObjectName("button_ok")
        self.buttonLayout.addWidget(self.button_ok)
        self.button_cancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_cancel.setObjectName("button_cancel")
        self.buttonLayout.addWidget(self.button_cancel)
        self.verticalLayout.addLayout(self.buttonLayout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Revision Control System"))
        self.title_label.setText(_translate("MainWindow", "Revision Control System"))
        self.desc_label.setText(_translate("MainWindow", "Embeds revision control info (git/svn/timestamp) into the gateware, accessible by software. This block has no signal ports."))
        self.label_app_src.setText(_translate("MainWindow", "Application revision info to capture"))
        self.app_src.setItemText(0, _translate("MainWindow", "timestamp"))
        self.app_src.setItemText(1, _translate("MainWindow", "git"))
        self.app_src.setItemText(2, _translate("MainWindow", "svn"))
        self.label_lib_src.setText(_translate("MainWindow", "CASPER libraries revision info to capture"))
        self.lib_src.setItemText(0, _translate("MainWindow", "timestamp"))
        self.lib_src.setItemText(1, _translate("MainWindow", "git"))
        self.lib_src.setItemText(2, _translate("MainWindow", "svn"))
        self.label_user_val.setText(_translate("MainWindow", "User specified value"))
        self.button_apply.setText(_translate("MainWindow", "Apply"))
        self.button_ok.setText(_translate("MainWindow", "OK"))
        self.button_cancel.setText(_translate("MainWindow", "Cancel"))
