# Form implementation for the Fixed to Float mask dialog.
# Hand-generated by casper_dsp/scripts/gen_block_gui.py to match the layout
# in ui/fixed_to_float.ui -- if PyQt6/pyuic6 is available, regenerate with:
#   pyuic6 ui/fixed_to_float.ui -o fixed_to_float_ui.py
# and keep both in sync by hand otherwise.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(560, 400)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)

        self.desc_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.desc_label.setWordWrap(True)
        self.desc_label.setObjectName("desc_label")
        self.verticalLayout.addWidget(self.desc_label)

        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.label_float_type = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_float_type.setObjectName("label_float_type")
        self.gridLayout.addWidget(self.label_float_type, 1, 0, 1, 1)
        self.float_type = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.float_type.setObjectName("float_type")
        self.float_type.addItem("")
        self.float_type.addItem("")
        self.gridLayout.addWidget(self.float_type, 1, 1, 1, 2)
        self.label_n_bits_in = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_n_bits_in.setObjectName("label_n_bits_in")
        self.gridLayout.addWidget(self.label_n_bits_in, 2, 0, 1, 1)
        self.n_bits_in = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.n_bits_in.setObjectName("n_bits_in")
        self.n_bits_in.setRange(1, 128)
        self.gridLayout.addWidget(self.n_bits_in, 2, 1, 1, 2)
        self.label_bin_pt = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_bin_pt.setObjectName("label_bin_pt")
        self.gridLayout.addWidget(self.label_bin_pt, 3, 0, 1, 1)
        self.bin_pt = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.bin_pt.setObjectName("bin_pt")
        self.bin_pt.setRange(0, 128)
        self.gridLayout.addWidget(self.bin_pt, 3, 1, 1, 2)
        self.label_num_vec = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_num_vec.setObjectName("label_num_vec")
        self.gridLayout.addWidget(self.label_num_vec, 4, 0, 1, 1)
        self.num_vec = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.num_vec.setObjectName("num_vec")
        self.num_vec.setRange(1, 64)
        self.gridLayout.addWidget(self.num_vec, 4, 1, 1, 2)
        self.label_csp_latency = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_csp_latency.setObjectName("label_csp_latency")
        self.gridLayout.addWidget(self.label_csp_latency, 5, 0, 1, 1)
        self.csp_latency = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.csp_latency.setObjectName("csp_latency")
        self.csp_latency.setRange(0, 32)
        self.gridLayout.addWidget(self.csp_latency, 5, 1, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.buttonLayout.addItem(spacerItem)
        self.button_apply = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_apply.setObjectName("button_apply")
        self.buttonLayout.addWidget(self.button_apply)
        self.button_ok = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_ok.setObjectName("button_ok")
        self.buttonLayout.addWidget(self.button_ok)
        self.button_cancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_cancel.setObjectName("button_cancel")
        self.buttonLayout.addWidget(self.button_cancel)
        self.verticalLayout.addLayout(self.buttonLayout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fixed to Float"))
        self.title_label.setText(_translate("MainWindow", "Fixed to Float"))
        self.desc_label.setText(_translate("MainWindow", "Convert fixed point vector (or bus of) to floating point."))
        self.label_float_type.setText(_translate("MainWindow", "float type"))
        self.float_type.setItemText(0, _translate("MainWindow", "Single"))
        self.float_type.setItemText(1, _translate("MainWindow", "Double"))
        self.label_n_bits_in.setText(_translate("MainWindow", "input word length"))
        self.label_bin_pt.setText(_translate("MainWindow", "input binary point"))
        self.label_num_vec.setText(_translate("MainWindow", "number vectors in bus"))
        self.label_csp_latency.setText(_translate("MainWindow", "Latency"))
        self.button_apply.setText(_translate("MainWindow", "Apply"))
        self.button_ok.setText(_translate("MainWindow", "OK"))
        self.button_cancel.setText(_translate("MainWindow", "Cancel"))
