# Form implementation for the Edge Detect mask dialog.
# Hand-generated by casper_dsp/scripts/gen_block_gui.py to match the layout
# in ui/edge_detect.ui -- if PyQt6/pyuic6 is available, regenerate with:
#   pyuic6 ui/edge_detect.ui -o edge_detect_ui.py
# and keep both in sync by hand otherwise.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(560, 280)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)

        self.desc_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.desc_label.setWordWrap(True)
        self.desc_label.setObjectName("desc_label")
        self.verticalLayout.addWidget(self.desc_label)

        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout.setColumnStretch(1, 1)
        self.label_edge_type = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_edge_type.setObjectName("label_edge_type")
        self.label_edge_type.setWordWrap(True)
        self.label_edge_type.setFixedWidth(129)
        self.gridLayout.addWidget(self.label_edge_type, 1, 0, 1, 1)
        self.edge_type = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.edge_type.setObjectName("edge_type")
        self.edge_type.addItem("")
        self.edge_type.addItem("")
        self.edge_type.addItem("")
        self.gridLayout.addWidget(self.edge_type, 1, 1, 1, 2)
        self.label_polarity = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_polarity.setObjectName("label_polarity")
        self.label_polarity.setWordWrap(True)
        self.label_polarity.setFixedWidth(129)
        self.gridLayout.addWidget(self.label_polarity, 2, 0, 1, 1)
        self.polarity = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.polarity.setObjectName("polarity")
        self.polarity.addItem("")
        self.polarity.addItem("")
        self.gridLayout.addWidget(self.polarity, 2, 1, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.buttonLayout.addItem(spacerItem)
        self.button_apply = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_apply.setObjectName("button_apply")
        self.buttonLayout.addWidget(self.button_apply)
        self.button_ok = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_ok.setObjectName("button_ok")
        self.buttonLayout.addWidget(self.button_ok)
        self.button_cancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_cancel.setObjectName("button_cancel")
        self.buttonLayout.addWidget(self.button_cancel)
        self.verticalLayout.addLayout(self.buttonLayout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Edge Detect"))
        self.title_label.setText(_translate("MainWindow", "Edge Detect"))
        self.desc_label.setText(_translate("MainWindow", "Output is active for one cycle after each edge of the specified type on the input."))
        self.label_edge_type.setText(_translate("MainWindow", "Edge Type"))
        self.edge_type.setItemText(0, _translate("MainWindow", "rising"))
        self.edge_type.setItemText(1, _translate("MainWindow", "falling"))
        self.edge_type.setItemText(2, _translate("MainWindow", "both"))
        self.label_polarity.setText(_translate("MainWindow", "Output Polarity"))
        self.polarity.setItemText(0, _translate("MainWindow", "active high"))
        self.polarity.setItemText(1, _translate("MainWindow", "active low"))
        self.button_apply.setText(_translate("MainWindow", "Apply"))
        self.button_ok.setText(_translate("MainWindow", "OK"))
        self.button_cancel.setText(_translate("MainWindow", "Cancel"))
