# Form implementation for the Simple BRAM Vector Accumulator mask dialog.
# Hand-generated by casper_dsp/scripts/gen_block_gui.py to match the layout
# in ui/simple_bram_vacc.ui -- if PyQt6/pyuic6 is available, regenerate with:
#   pyuic6 ui/simple_bram_vacc.ui -o simple_bram_vacc_ui.py
# and keep both in sync by hand otherwise.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(578, 360)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)

        self.desc_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.desc_label.setWordWrap(True)
        self.desc_label.setObjectName("desc_label")
        self.verticalLayout.addWidget(self.desc_label)

        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout.setColumnStretch(1, 1)
        self.label_vec_len = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_vec_len.setObjectName("label_vec_len")
        self.label_vec_len.setWordWrap(True)
        self.label_vec_len.setFixedWidth(178)
        self.gridLayout.addWidget(self.label_vec_len, 1, 0, 1, 1)
        self.vec_len = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.vec_len.setObjectName("vec_len")
        self.gridLayout.addWidget(self.vec_len, 1, 1, 1, 2)
        self.label_arith_type = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_arith_type.setObjectName("label_arith_type")
        self.label_arith_type.setWordWrap(True)
        self.label_arith_type.setFixedWidth(178)
        self.gridLayout.addWidget(self.label_arith_type, 2, 0, 1, 1)
        self.arith_type = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.arith_type.setObjectName("arith_type")
        self.arith_type.addItem("")
        self.arith_type.addItem("")
        self.gridLayout.addWidget(self.arith_type, 2, 1, 1, 2)
        self.label_n_bits = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_n_bits.setObjectName("label_n_bits")
        self.label_n_bits.setWordWrap(True)
        self.label_n_bits.setFixedWidth(178)
        self.gridLayout.addWidget(self.label_n_bits, 3, 0, 1, 1)
        self.n_bits = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.n_bits.setObjectName("n_bits")
        self.n_bits.setRange(1, 128)
        self.gridLayout.addWidget(self.n_bits, 3, 1, 1, 2)
        self.label_bin_pt = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_bin_pt.setObjectName("label_bin_pt")
        self.label_bin_pt.setWordWrap(True)
        self.label_bin_pt.setFixedWidth(178)
        self.gridLayout.addWidget(self.label_bin_pt, 4, 0, 1, 1)
        self.bin_pt = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.bin_pt.setObjectName("bin_pt")
        self.bin_pt.setRange(0, 128)
        self.gridLayout.addWidget(self.bin_pt, 4, 1, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.buttonLayout.addItem(spacerItem)
        self.button_apply = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_apply.setObjectName("button_apply")
        self.buttonLayout.addWidget(self.button_apply)
        self.button_ok = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_ok.setObjectName("button_ok")
        self.buttonLayout.addWidget(self.button_ok)
        self.button_cancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_cancel.setObjectName("button_cancel")
        self.buttonLayout.addWidget(self.button_cancel)
        self.verticalLayout.addLayout(self.buttonLayout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simple BRAM Vector Accumulator"))
        self.title_label.setText(_translate("MainWindow", "Simple BRAM Vector Accumulator"))
        self.desc_label.setText(_translate("MainWindow", "This simple vector accumulator is based on a shift register. It outputs its previous accumulated vector after a new_acc pulse is received."))
        self.label_vec_len.setText(_translate("MainWindow", "Vector length:"))
        self.label_arith_type.setText(_translate("MainWindow", "Output type:"))
        self.arith_type.setItemText(0, _translate("MainWindow", "Signed"))
        self.arith_type.setItemText(1, _translate("MainWindow", "Unsigned"))
        self.label_n_bits.setText(_translate("MainWindow", "Bit width (output):"))
        self.label_bin_pt.setText(_translate("MainWindow", "Binary point (output):"))
        self.button_apply.setText(_translate("MainWindow", "Apply"))
        self.button_ok.setText(_translate("MainWindow", "OK"))
        self.button_cancel.setText(_translate("MainWindow", "Cancel"))
