# Form implementation for the Munge mask dialog.
# Hand-generated by casper_dsp/scripts/gen_block_gui.py to match the layout
# in ui/munge.ui -- if PyQt6/pyuic6 is available, regenerate with:
#   pyuic6 ui/munge.ui -o munge_ui.py
# and keep both in sync by hand otherwise.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(560, 360)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)

        self.desc_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.desc_label.setWordWrap(True)
        self.desc_label.setObjectName("desc_label")
        self.verticalLayout.addWidget(self.desc_label)

        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.label_total_bits = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_total_bits.setObjectName("label_total_bits")
        self.gridLayout.addWidget(self.label_total_bits, 1, 0, 1, 1)
        self.total_bits = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.total_bits.setObjectName("total_bits")
        self.total_bits.setRange(1, 4096)
        self.gridLayout.addWidget(self.total_bits, 1, 1, 1, 2)
        self.label_divisions = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_divisions.setObjectName("label_divisions")
        self.gridLayout.addWidget(self.label_divisions, 2, 0, 1, 1)
        self.divisions = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.divisions.setObjectName("divisions")
        self.divisions.setRange(1, 64)
        self.gridLayout.addWidget(self.divisions, 2, 1, 1, 2)
        self.label_size_bits = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_size_bits.setObjectName("label_size_bits")
        self.gridLayout.addWidget(self.label_size_bits, 3, 0, 1, 1)
        self.size_bits = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.size_bits.setObjectName("size_bits")
        self.size_bits.setRange(1, 4096)
        self.gridLayout.addWidget(self.size_bits, 3, 1, 1, 2)
        self.label_packing_order = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_packing_order.setObjectName("label_packing_order")
        self.gridLayout.addWidget(self.label_packing_order, 4, 0, 1, 1)
        self.packing_order = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.packing_order.setObjectName("packing_order")
        self.gridLayout.addWidget(self.packing_order, 4, 1, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.buttonLayout.addItem(spacerItem)
        self.button_apply = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_apply.setObjectName("button_apply")
        self.buttonLayout.addWidget(self.button_apply)
        self.button_ok = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_ok.setObjectName("button_ok")
        self.buttonLayout.addWidget(self.button_ok)
        self.button_cancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_cancel.setObjectName("button_cancel")
        self.buttonLayout.addWidget(self.button_cancel)
        self.verticalLayout.addLayout(self.buttonLayout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Munge"))
        self.title_label.setText(_translate("MainWindow", "Munge"))
        self.desc_label.setText(_translate("MainWindow", "Splits an input bus into the specified number of divisions and then recombines them in the order specified (most significant division = 0, least = number of divisions - 1)."))
        self.label_total_bits.setText(_translate("MainWindow", "Total Bits (input/output bus width)"))
        self.label_divisions.setText(_translate("MainWindow", "Number of Divisions"))
        self.label_size_bits.setText(_translate("MainWindow", "Division Size (bits, equal for every division)"))
        self.label_packing_order.setText(_translate("MainWindow", "Packing Order (division indices, e.g. {3,2,1,0})"))
        self.button_apply.setText(_translate("MainWindow", "Apply"))
        self.button_ok.setText(_translate("MainWindow", "OK"))
        self.button_cancel.setText(_translate("MainWindow", "Cancel"))
