# Form implementation for the Parallel to Serial Converter mask dialog.
# Hand-generated by casper_dsp/scripts/gen_block_gui.py to match the layout
# in ui/parallel_to_serial_converter.ui -- if PyQt6/pyuic6 is available, regenerate with:
#   pyuic6 ui/parallel_to_serial_converter.ui -o parallel_to_serial_converter_ui.py
# and keep both in sync by hand otherwise.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(560, 280)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)

        self.desc_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.desc_label.setWordWrap(True)
        self.desc_label.setObjectName("desc_label")
        self.verticalLayout.addWidget(self.desc_label)

        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout.setColumnStretch(1, 1)
        self.label_pin_width = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_pin_width.setObjectName("label_pin_width")
        self.label_pin_width.setWordWrap(True)
        self.label_pin_width.setMaximumWidth(164)
        self.gridLayout.addWidget(self.label_pin_width, 1, 0, 1, 1)
        self.pin_width = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.pin_width.setObjectName("pin_width")
        self.pin_width.setRange(1, 8192)
        self.gridLayout.addWidget(self.pin_width, 1, 1, 1, 2)
        self.label_sout_width = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_sout_width.setObjectName("label_sout_width")
        self.label_sout_width.setWordWrap(True)
        self.label_sout_width.setMaximumWidth(164)
        self.gridLayout.addWidget(self.label_sout_width, 2, 0, 1, 1)
        self.sout_width = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.sout_width.setObjectName("sout_width")
        self.sout_width.setRange(1, 8192)
        self.gridLayout.addWidget(self.sout_width, 2, 1, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.buttonLayout.addItem(spacerItem)
        self.button_apply = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_apply.setObjectName("button_apply")
        self.buttonLayout.addWidget(self.button_apply)
        self.button_ok = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_ok.setObjectName("button_ok")
        self.buttonLayout.addWidget(self.button_ok)
        self.button_cancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_cancel.setObjectName("button_cancel")
        self.buttonLayout.addWidget(self.button_cancel)
        self.verticalLayout.addLayout(self.buttonLayout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Parallel to Serial Converter"))
        self.title_label.setText(_translate("MainWindow", "Parallel to Serial Converter"))
        self.desc_label.setText(_translate("MainWindow", "This block takes as input a parallel bus of specified width. When the load signal 'ld' is asserted, this data is broken into pieces of width specified by the serial output width and stored into different registers chained to form a shift register. If the 'shift' input is subsequently asserted, the shift register returns as output a new piece of data of width sout_width. This data is the next least significant piece of the original bus. The converter serializes SMALL ENDIAN."))
        self.label_pin_width.setText(_translate("MainWindow", "Parallel Input Width"))
        self.label_sout_width.setText(_translate("MainWindow", "Serial Output Width"))
        self.button_apply.setText(_translate("MainWindow", "Apply"))
        self.button_ok.setText(_translate("MainWindow", "OK"))
        self.button_cancel.setText(_translate("MainWindow", "Cancel"))
