# Form implementation for the Bus Scale mask dialog.
# Hand-generated by casper_dsp/scripts/gen_block_gui.py to match the layout
# in ui/bus_scale.ui -- if PyQt6/pyuic6 is available, regenerate with:
#   pyuic6 ui/bus_scale.ui -o bus_scale_ui.py
# and keep both in sync by hand otherwise.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(560, 440)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)

        self.desc_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.desc_label.setWordWrap(True)
        self.desc_label.setObjectName("desc_label")
        self.verticalLayout.addWidget(self.desc_label)

        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.label_n_bits_in = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_n_bits_in.setObjectName("label_n_bits_in")
        self.gridLayout.addWidget(self.label_n_bits_in, 1, 0, 1, 1)
        self.n_bits_in = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.n_bits_in.setObjectName("n_bits_in")
        self.gridLayout.addWidget(self.n_bits_in, 1, 1, 1, 2)
        self.label_bin_pt_in = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_bin_pt_in.setObjectName("label_bin_pt_in")
        self.gridLayout.addWidget(self.label_bin_pt_in, 2, 0, 1, 1)
        self.bin_pt_in = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.bin_pt_in.setObjectName("bin_pt_in")
        self.gridLayout.addWidget(self.bin_pt_in, 2, 1, 1, 2)
        self.label_type_in = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_type_in.setObjectName("label_type_in")
        self.gridLayout.addWidget(self.label_type_in, 3, 0, 1, 1)
        self.type_in = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.type_in.setObjectName("type_in")
        self.gridLayout.addWidget(self.type_in, 3, 1, 1, 2)
        self.label_cmplx = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_cmplx.setObjectName("label_cmplx")
        self.gridLayout.addWidget(self.label_cmplx, 4, 0, 1, 1)
        self.cmplx = QtWidgets.QCheckBox(parent=self.scrollAreaWidgetContents)
        self.cmplx.setObjectName("cmplx")
        self.gridLayout.addWidget(self.cmplx, 4, 1, 1, 2)
        self.label_scale_factor = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_scale_factor.setObjectName("label_scale_factor")
        self.gridLayout.addWidget(self.label_scale_factor, 5, 0, 1, 1)
        self.scale_factor = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.scale_factor.setObjectName("scale_factor")
        self.gridLayout.addWidget(self.scale_factor, 5, 1, 1, 2)
        self.label_misc = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_misc.setObjectName("label_misc")
        self.gridLayout.addWidget(self.label_misc, 6, 0, 1, 1)
        self.misc = QtWidgets.QCheckBox(parent=self.scrollAreaWidgetContents)
        self.misc.setObjectName("misc")
        self.gridLayout.addWidget(self.misc, 6, 1, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.buttonLayout.addItem(spacerItem)
        self.button_apply = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_apply.setObjectName("button_apply")
        self.buttonLayout.addWidget(self.button_apply)
        self.button_ok = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_ok.setObjectName("button_ok")
        self.buttonLayout.addWidget(self.button_ok)
        self.button_cancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_cancel.setObjectName("button_cancel")
        self.buttonLayout.addWidget(self.button_cancel)
        self.verticalLayout.addLayout(self.buttonLayout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bus Scale"))
        self.title_label.setText(_translate("MainWindow", "Bus Scale"))
        self.desc_label.setText(_translate("MainWindow", "Convert components of busses"))
        self.label_n_bits_in.setText(_translate("MainWindow", "input bit widths"))
        self.label_bin_pt_in.setText(_translate("MainWindow", "input binary points"))
        self.label_type_in.setText(_translate("MainWindow", "input types"))
        self.label_cmplx.setText(_translate("MainWindow", "input complex"))
        self.label_scale_factor.setText(_translate("MainWindow", "scale factor (2^?)"))
        self.label_misc.setText(_translate("MainWindow", "misc support"))
        self.button_apply.setText(_translate("MainWindow", "Apply"))
        self.button_ok.setText(_translate("MainWindow", "OK"))
        self.button_cancel.setText(_translate("MainWindow", "Cancel"))
