# Form implementation for the Power mask dialog.
# Hand-generated by casper_dsp/scripts/gen_block_gui.py to match the layout
# in ui/power.ui -- if PyQt6/pyuic6 is available, regenerate with:
#   pyuic6 ui/power.ui -o power_ui.py
# and keep both in sync by hand otherwise.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(560, 320)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)

        self.desc_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.desc_label.setWordWrap(True)
        self.desc_label.setObjectName("desc_label")
        self.verticalLayout.addWidget(self.desc_label)

        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout.setColumnStretch(1, 1)
        self.label_bit_width = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_bit_width.setObjectName("label_bit_width")
        self.label_bit_width.setWordWrap(True)
        self.label_bit_width.setMaximumWidth(108)
        self.gridLayout.addWidget(self.label_bit_width, 1, 0, 1, 1)
        self.bit_width = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.bit_width.setObjectName("bit_width")
        self.bit_width.setRange(1, 128)
        self.gridLayout.addWidget(self.bit_width, 1, 1, 1, 2)
        self.label_add_latency = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_add_latency.setObjectName("label_add_latency")
        self.label_add_latency.setWordWrap(True)
        self.label_add_latency.setMaximumWidth(108)
        self.gridLayout.addWidget(self.label_add_latency, 2, 0, 1, 1)
        self.add_latency = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.add_latency.setObjectName("add_latency")
        self.add_latency.setRange(0, 32)
        self.gridLayout.addWidget(self.add_latency, 2, 1, 1, 2)
        self.label_mult_latency = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_mult_latency.setObjectName("label_mult_latency")
        self.label_mult_latency.setWordWrap(True)
        self.label_mult_latency.setMaximumWidth(108)
        self.gridLayout.addWidget(self.label_mult_latency, 3, 0, 1, 1)
        self.mult_latency = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.mult_latency.setObjectName("mult_latency")
        self.mult_latency.setRange(0, 32)
        self.gridLayout.addWidget(self.mult_latency, 3, 1, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.buttonLayout.addItem(spacerItem)
        self.button_apply = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_apply.setObjectName("button_apply")
        self.buttonLayout.addWidget(self.button_apply)
        self.button_ok = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_ok.setObjectName("button_ok")
        self.buttonLayout.addWidget(self.button_ok)
        self.button_cancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_cancel.setObjectName("button_cancel")
        self.buttonLayout.addWidget(self.button_cancel)
        self.verticalLayout.addLayout(self.buttonLayout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Power"))
        self.title_label.setText(_translate("MainWindow", "Power"))
        self.desc_label.setText(_translate("MainWindow", "Squares real and imaginary components of complex input and adds them."))
        self.label_bit_width.setText(_translate("MainWindow", "Bit Width"))
        self.label_add_latency.setText(_translate("MainWindow", "Add Latency"))
        self.label_mult_latency.setText(_translate("MainWindow", "Mult Latency"))
        self.button_apply.setText(_translate("MainWindow", "Apply"))
        self.button_ok.setText(_translate("MainWindow", "OK"))
        self.button_cancel.setText(_translate("MainWindow", "Cancel"))
