# Form implementation for the Bus Constant mask dialog.
# Hand-generated by casper_dsp/scripts/gen_block_gui.py to match the layout
# in ui/bus_constant.ui -- if PyQt6/pyuic6 is available, regenerate with:
#   pyuic6 ui/bus_constant.ui -o bus_constant_ui.py
# and keep both in sync by hand otherwise.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(560, 360)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)

        self.desc_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.desc_label.setWordWrap(True)
        self.desc_label.setObjectName("desc_label")
        self.verticalLayout.addWidget(self.desc_label)

        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout.setColumnStretch(1, 1)
        self.label_values = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_values.setObjectName("label_values")
        self.label_values.setWordWrap(True)
        self.label_values.setMaximumWidth(115)
        self.gridLayout.addWidget(self.label_values, 1, 0, 1, 1)
        self.values = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.values.setObjectName("values")
        self.gridLayout.addWidget(self.values, 1, 1, 1, 2)
        self.label_n_bits = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_n_bits.setObjectName("label_n_bits")
        self.label_n_bits.setWordWrap(True)
        self.label_n_bits.setMaximumWidth(115)
        self.gridLayout.addWidget(self.label_n_bits, 2, 0, 1, 1)
        self.n_bits = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.n_bits.setObjectName("n_bits")
        self.gridLayout.addWidget(self.n_bits, 2, 1, 1, 2)
        self.label_bin_pts = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_bin_pts.setObjectName("label_bin_pts")
        self.label_bin_pts.setWordWrap(True)
        self.label_bin_pts.setMaximumWidth(115)
        self.gridLayout.addWidget(self.label_bin_pts, 3, 0, 1, 1)
        self.bin_pts = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.bin_pts.setObjectName("bin_pts")
        self.gridLayout.addWidget(self.bin_pts, 3, 1, 1, 2)
        self.label_types = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_types.setObjectName("label_types")
        self.label_types.setWordWrap(True)
        self.label_types.setMaximumWidth(115)
        self.gridLayout.addWidget(self.label_types, 4, 0, 1, 1)
        self.types = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.types.setObjectName("types")
        self.gridLayout.addWidget(self.types, 4, 1, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.buttonLayout.addItem(spacerItem)
        self.button_apply = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_apply.setObjectName("button_apply")
        self.buttonLayout.addWidget(self.button_apply)
        self.button_ok = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_ok.setObjectName("button_ok")
        self.buttonLayout.addWidget(self.button_ok)
        self.button_cancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_cancel.setObjectName("button_cancel")
        self.buttonLayout.addWidget(self.button_cancel)
        self.verticalLayout.addLayout(self.buttonLayout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bus Constant"))
        self.title_label.setText(_translate("MainWindow", "Bus Constant"))
        self.desc_label.setText(_translate("MainWindow", "Combine constants into a bus"))
        self.label_values.setText(_translate("MainWindow", "values"))
        self.label_n_bits.setText(_translate("MainWindow", "bit widths"))
        self.label_bin_pts.setText(_translate("MainWindow", "binary points"))
        self.label_types.setText(_translate("MainWindow", "data type"))
        self.button_apply.setText(_translate("MainWindow", "Apply"))
        self.button_ok.setText(_translate("MainWindow", "OK"))
        self.button_cancel.setText(_translate("MainWindow", "Cancel"))
