# Form implementation for the adc_mkid_4x mask dialog.
# Hand-generated by casper_xps/scripts/gen_block_gui.py to match the layout
# in ui/adc_mkid_4x.ui -- if PyQt6/pyuic6 is available, regenerate with:
#   pyuic6 ui/adc_mkid_4x.ui -o adc_mkid_4x_ui.py
# and keep both in sync by hand otherwise.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(564, 280)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)

        self.desc_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.desc_label.setWordWrap(True)
        self.desc_label.setObjectName("desc_label")
        self.verticalLayout.addWidget(self.desc_label)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout.setColumnStretch(1, 1)
        self.label_adc_brd = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_adc_brd.setObjectName("label_adc_brd")
        self.label_adc_brd.setWordWrap(True)
        self.label_adc_brd.setFixedWidth(164)
        self.gridLayout.addWidget(self.label_adc_brd, 1, 0, 1, 1)
        self.adc_brd = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.adc_brd.setObjectName("adc_brd")
        self.adc_brd.addItem("")
        self.adc_brd.addItem("")
        self.gridLayout.addWidget(self.adc_brd, 1, 1, 1, 2)
        self.label_adc_clk_rate = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_adc_clk_rate.setObjectName("label_adc_clk_rate")
        self.label_adc_clk_rate.setWordWrap(True)
        self.label_adc_clk_rate.setFixedWidth(164)
        self.gridLayout.addWidget(self.label_adc_clk_rate, 2, 0, 1, 1)
        self.adc_clk_rate = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.adc_clk_rate.setObjectName("adc_clk_rate")
        self.gridLayout.addWidget(self.adc_clk_rate, 2, 1, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.buttonLayout.addItem(spacerItem)
        self.button_apply = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_apply.setObjectName("button_apply")
        self.buttonLayout.addWidget(self.button_apply)
        self.button_ok = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_ok.setObjectName("button_ok")
        self.buttonLayout.addWidget(self.button_ok)
        self.button_cancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_cancel.setObjectName("button_cancel")
        self.buttonLayout.addWidget(self.button_cancel)
        self.verticalLayout.addLayout(self.buttonLayout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "adc_mkid_4x"))
        self.title_label.setText(_translate("MainWindow", "adc_mkid_4x"))
        self.desc_label.setText(_translate("MainWindow", "Interface block for the MKID 12-bits ADC board (2xADS54RF63)."))
        self.label_adc_brd.setText(_translate("MainWindow", "ADC Board"))
        self.adc_brd.setItemText(0, _translate("MainWindow", "0"))
        self.adc_brd.setItemText(1, _translate("MainWindow", "1"))
        self.label_adc_clk_rate.setText(_translate("MainWindow", "ADC Clock Rate (MHz)"))
        self.button_apply.setText(_translate("MainWindow", "Apply"))
        self.button_ok.setText(_translate("MainWindow", "OK"))
        self.button_cancel.setText(_translate("MainWindow", "Cancel"))
