# Form implementation for the Bus Expand mask dialog.
# Hand-generated by casper_dsp/scripts/gen_block_gui.py to match the layout
# in ui/bus_expand.ui -- if PyQt6/pyuic6 is available, regenerate with:
#   pyuic6 ui/bus_expand.ui -o bus_expand_ui.py
# and keep both in sync by hand otherwise.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(865, 280)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)

        self.desc_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.desc_label.setWordWrap(True)
        self.desc_label.setObjectName("desc_label")
        self.verticalLayout.addWidget(self.desc_label)

        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout.setColumnStretch(1, 1)
        self.label_ndivision = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_ndivision.setObjectName("label_ndivision")
        self.label_ndivision.setWordWrap(True)
        self.label_ndivision.setMaximumWidth(465)
        self.gridLayout.addWidget(self.label_ndivision, 1, 0, 1, 1)
        self.ndivision = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.ndivision.setObjectName("ndivision")
        self.ndivision.setRange(1, 64)
        self.gridLayout.addWidget(self.ndivision, 1, 1, 1, 2)
        self.label_bit_division = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_bit_division.setObjectName("label_bit_division")
        self.label_bit_division.setWordWrap(True)
        self.label_bit_division.setMaximumWidth(465)
        self.gridLayout.addWidget(self.label_bit_division, 2, 0, 1, 1)
        self.bit_division = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.bit_division.setObjectName("bit_division")
        self.gridLayout.addWidget(self.bit_division, 2, 1, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.buttonLayout.addItem(spacerItem)
        self.button_apply = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_apply.setObjectName("button_apply")
        self.buttonLayout.addWidget(self.button_apply)
        self.button_ok = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_ok.setObjectName("button_ok")
        self.buttonLayout.addWidget(self.button_ok)
        self.button_cancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_cancel.setObjectName("button_cancel")
        self.buttonLayout.addWidget(self.button_cancel)
        self.verticalLayout.addLayout(self.buttonLayout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bus Expand"))
        self.title_label.setText(_translate("MainWindow", "Bus Expand"))
        self.desc_label.setText(_translate("MainWindow", "Expands a 'bus' made using a bus_create or Xilinx concat block. The input is divided into the specified number of outputs, each with the specified bit width. Divisions are made from the most significant bit."))
        self.label_ndivision.setText(_translate("MainWindow", "Number of Division:"))
        self.label_bit_division.setText(_translate("MainWindow", "Bit width of each output (vector, length = Number of Division):"))
        self.button_apply.setText(_translate("MainWindow", "Apply"))
        self.button_ok.setText(_translate("MainWindow", "OK"))
        self.button_cancel.setText(_translate("MainWindow", "Cancel"))
