# Form implementation for the DSP48E BRAM Vector Accumulator mask dialog.
# Hand-generated by casper_dsp/scripts/gen_block_gui.py to match the layout
# in ui/dsp48e_bram_vacc.ui -- if PyQt6/pyuic6 is available, regenerate with:
#   pyuic6 ui/dsp48e_bram_vacc.ui -o dsp48e_bram_vacc_ui.py
# and keep both in sync by hand otherwise.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(560, 400)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)

        self.desc_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.desc_label.setWordWrap(True)
        self.desc_label.setObjectName("desc_label")
        self.verticalLayout.addWidget(self.desc_label)

        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.label_vec_len = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_vec_len.setObjectName("label_vec_len")
        self.gridLayout.addWidget(self.label_vec_len, 1, 0, 1, 1)
        self.vec_len = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.vec_len.setObjectName("vec_len")
        self.gridLayout.addWidget(self.vec_len, 1, 1, 1, 2)
        self.label_arith_type = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_arith_type.setObjectName("label_arith_type")
        self.gridLayout.addWidget(self.label_arith_type, 2, 0, 1, 1)
        self.arith_type = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.arith_type.setObjectName("arith_type")
        self.arith_type.addItem("")
        self.arith_type.addItem("")
        self.gridLayout.addWidget(self.arith_type, 2, 1, 1, 2)
        self.label_bin_pt_in = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_bin_pt_in.setObjectName("label_bin_pt_in")
        self.gridLayout.addWidget(self.label_bin_pt_in, 3, 0, 1, 1)
        self.bin_pt_in = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.bin_pt_in.setObjectName("bin_pt_in")
        self.bin_pt_in.setRange(0, 32)
        self.gridLayout.addWidget(self.bin_pt_in, 3, 1, 1, 2)
        self.label_n_bits_out = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_n_bits_out.setObjectName("label_n_bits_out")
        self.gridLayout.addWidget(self.label_n_bits_out, 4, 0, 1, 1)
        self.n_bits_out = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.n_bits_out.setObjectName("n_bits_out")
        self.n_bits_out.setRange(1, 32)
        self.gridLayout.addWidget(self.n_bits_out, 4, 1, 1, 2)
        self.label_n_bits_in = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_n_bits_in.setObjectName("label_n_bits_in")
        self.gridLayout.addWidget(self.label_n_bits_in, 5, 0, 1, 1)
        self.n_bits_in = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.n_bits_in.setObjectName("n_bits_in")
        self.n_bits_in.setRange(1, 32)
        self.gridLayout.addWidget(self.n_bits_in, 5, 1, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.buttonLayout.addItem(spacerItem)
        self.button_apply = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_apply.setObjectName("button_apply")
        self.buttonLayout.addWidget(self.button_apply)
        self.button_ok = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_ok.setObjectName("button_ok")
        self.buttonLayout.addWidget(self.button_ok)
        self.button_cancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_cancel.setObjectName("button_cancel")
        self.buttonLayout.addWidget(self.button_cancel)
        self.verticalLayout.addLayout(self.buttonLayout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DSP48E BRAM Vector Accumulator"))
        self.title_label.setText(_translate("MainWindow", "DSP48E BRAM Vector Accumulator"))
        self.desc_label.setText(_translate("MainWindow", "A vector accumulator modeled after a shift register, replacing the adder+mux with a single DSP48E for high-speed compilation. Output bit width cannot exceed 32; output binary point matches the input. n_bits_in is added here (not a casper_library mask param) for the Xcos port's explicit input width."))
        self.label_vec_len.setText(_translate("MainWindow", "Vector length:"))
        self.label_arith_type.setText(_translate("MainWindow", "Output type:"))
        self.arith_type.setItemText(0, _translate("MainWindow", "Unsigned"))
        self.arith_type.setItemText(1, _translate("MainWindow", "Signed  (2's comp)"))
        self.label_bin_pt_in.setText(_translate("MainWindow", "Binary point (input):"))
        self.label_n_bits_out.setText(_translate("MainWindow", "Bit width (output):"))
        self.label_n_bits_in.setText(_translate("MainWindow", "Bit Width In (added for Xcos; not a casper_library mask param)"))
        self.button_apply.setText(_translate("MainWindow", "Apply"))
        self.button_ok.setText(_translate("MainWindow", "OK"))
        self.button_cancel.setText(_translate("MainWindow", "Cancel"))
