# Form implementation for the adc_sim mask dialog.
# Hand-generated by casper_xps/scripts/gen_block_gui.py to match the layout
# in ui/adc_sim.ui -- if PyQt6/pyuic6 is available, regenerate with:
#   pyuic6 ui/adc_sim.ui -o adc_sim_ui.py
# and keep both in sync by hand otherwise.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(592, 280)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)

        self.desc_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.desc_label.setWordWrap(True)
        self.desc_label.setObjectName("desc_label")
        self.verticalLayout.addWidget(self.desc_label)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout.setColumnStretch(1, 1)
        self.label_nStreams = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_nStreams.setObjectName("label_nStreams")
        self.label_nStreams.setWordWrap(True)
        self.label_nStreams.setFixedWidth(192)
        self.gridLayout.addWidget(self.label_nStreams, 1, 0, 1, 1)
        self.nStreams = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.nStreams.setObjectName("nStreams")
        self.gridLayout.addWidget(self.nStreams, 1, 1, 1, 2)
        self.label_bit_width = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_bit_width.setObjectName("label_bit_width")
        self.label_bit_width.setWordWrap(True)
        self.label_bit_width.setFixedWidth(192)
        self.gridLayout.addWidget(self.label_bit_width, 2, 0, 1, 1)
        self.bit_width = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.bit_width.setObjectName("bit_width")
        self.gridLayout.addWidget(self.bit_width, 2, 1, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.buttonLayout.addItem(spacerItem)
        self.button_apply = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_apply.setObjectName("button_apply")
        self.buttonLayout.addWidget(self.button_apply)
        self.button_ok = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_ok.setObjectName("button_ok")
        self.buttonLayout.addWidget(self.button_ok)
        self.button_cancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_cancel.setObjectName("button_cancel")
        self.buttonLayout.addWidget(self.button_cancel)
        self.verticalLayout.addLayout(self.buttonLayout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "adc_sim"))
        self.title_label.setText(_translate("MainWindow", "adc_sim"))
        self.desc_label.setText(_translate("MainWindow", "This block simulates the behavior of a demuxed ADC, which takes\nas input a waveform and returns digital samples in parallel at\na slower rate.  \n\nThis block is used to simulate the behavior"))
        self.label_nStreams.setText(_translate("MainWindow", "Number of Output Streams"))
        self.label_bit_width.setText(_translate("MainWindow", "Sample Bit Width"))
        self.button_apply.setText(_translate("MainWindow", "Apply"))
        self.button_ok.setText(_translate("MainWindow", "OK"))
        self.button_cancel.setText(_translate("MainWindow", "Cancel"))
