// bus_create: Xcos block definition, PyQt6-mask pattern.
// Generated by casper_dsp/scripts/gen_sci_block.py -- review the port
// topology and TODOs below before relying on this in a real design.
function [x, y, typ] = bus_create(job, arg1, arg2)
    x=[];y=[];typ=[];
    select job
    case 'set' then
        x = arg1;
        export_exprs_to_tmpdir(x);
        bconfig = run_mask(x);
        x = update_exprs_from_tmpdir(x);
        x = bus_create_update_ports(x, bconfig);
    case 'define' then
        tag = 'bus_create';
        model = scicos_model();
        model.sim = list(tag, 4);
        model.blocktype = 'c';
        model.rpar = [];
        exprs = [];
        gr_i = [];
        [iports_index, iports_label] = bus_create_create_iports(2);
        model.in = iports_index;
        // one bit width per input; default matches bus_create.json's "bit_widths"
        model.in2 = evstr('[8,8]');
        [oports_index, oports_label] = bus_create_create_oports(2);
        model.out = oports_index;
        // output bus width is the sum of all input widths (concatenation)
        model.out2 = [sum(evstr('[8,8]'))];
        // model.label doubles as the on-diagram display text (Scicos aliases
        // it with graphics.id); category is derived separately by
        // get_block_type.sci via file-probe, so this is free to be the name.
        model.label = tag;
        // icon size [5 7] scaled directly from bus_create's own
        // casper_library icon (50x78 px) -- see SKILL.md Step 3b
        x=standard_define([6 8.4],model,exprs,gr_i)
        x.graphics.in_label = iports_label;
        x.graphics.out_label = oports_label;
        // block name (shown below the fill color) comes from the
        // "name" JSON key -- init_exprs populates exprs from the
        // template first, so exprs(1) is its default value here
        x = init_exprs(x);
        x.graphics.style = bus_create_build_style(x.graphics.exprs(1));
        debug_info('bus_create block loaded...')
    end
endfunction

function [ports_index, ports_label] = bus_create_create_iports(factor)
    ports_label = [];
    ports_index = [];
    for i = 1:factor
        // 1-based, matching casper_library bus_create_init.m's in1, in2, ...
        ports_label = [ports_label, 'in' + string(i)];
        ports_index = [ports_index, 0 + (i - 1) * 1 + 1];
    end
endfunction

function [ports_index, ports_label] = bus_create_create_oports(factor)
    ports_label = ['bus_out'];
    ports_index = [1];
endfunction

function [style] = bus_create_build_style(name)
    // strip mxGraph's own style-string delimiters so a user-typed
    // name can never corrupt the rest of the style string
    name = strsubst(string(name), ';', '');
    name = strsubst(name, '=', '');
    style = 'shape=rectangle;fillColor=#90EE90;strokeColor=black;fontColor=black;fontSize=12;align=center;verticalAlign=top;verticalLabelPosition=bottom;noLabel=0;displayedLabel=' + name + ';whiteSpace=wrap;html=1;spacing=4;';
endfunction

function [x] = bus_create_update_ports(obj, bconfigfn)
    x = obj;
    bconfig = fromJSON(bconfigfn, 'file');
    p = bconfig('parameters');
    graphics = obj.graphics;
    exprs = graphics.exprs;
    model = obj.model;
    factor = strtod(p('inputNum'));
    evtin = [];
    evtout = [];
    [iports_index, iports_label] = bus_create_create_iports(factor);
    [oports_index, oports_label] = bus_create_create_oports(factor);
    // port I/O type: 1 = REAL (see set_io() docs); this mirrors wbfft/bus_expand,
    // which don't distinguish port datatypes any further
    io_in = [iports_index; iports_index];
    io_out = [oports_index; oports_index];
    io_in_type = ones(1, length(iports_index));
    io_out_type = ones(1, length(oports_index));
    [model, graphics, ok] = set_io(model, graphics, list(io_in', io_in_type), list(io_out', io_out_type), evtin, evtout);
    model.in = iports_index;
    // one bit width per input, read straight from the "bit_widths" vector
    // (e.g. "[8,8]"); NOT a uniform width * factor like wbfft's data ports
    model.in2 = evstr(p('bit_widths'));
    model.out = oports_index;
    // output bus width is the sum of all input widths (concatenation)
    model.out2 = [sum(evstr(p('bit_widths')))];
    graphics.in_label = iports_label;
    graphics.out_label = oports_label;
    graphics.style = bus_create_build_style(p('name'));
    graphics.exprs = exprs;
    x.graphics = graphics;
    x.model = model;
endfunction
