// bus_expand: Xcos block definition, PyQt6-mask pattern.
// Generated by casper_dsp/scripts/gen_sci_block.py -- review the port
// topology and TODOs below before relying on this in a real design.
function [x, y, typ] = bus_expand(job, arg1, arg2)
    x=[];y=[];typ=[];
    select job
    case 'set' then
        x = arg1;
        export_exprs_to_tmpdir(x);
        bconfig = run_mask(x);
        x = update_exprs_from_tmpdir(x);
        x = bus_expand_update_ports(x, bconfig);
    case 'define' then
        tag = 'bus_expand';
        model = scicos_model();
        model.sim = list(tag, 4);
        model.blocktype = 'c';
        model.rpar = [];
        exprs = [];
        gr_i = [];
        [iports_index, iports_label] = bus_expand_create_iports(4);
        model.in = iports_index;
        // input bus width is the sum of all output widths (it's being split)
        model.in2 = [sum(evstr('[8,8,8,8]'))];
        [oports_index, oports_label] = bus_expand_create_oports(4);
        model.out = oports_index;
        // one bit width per output; default matches bus_expand.json's "bit_division"
        model.out2 = evstr('[8,8,8,8]');
        // model.label doubles as the on-diagram display text (Scicos aliases
        // it with graphics.id); category is derived separately by
        // get_block_type.sci via file-probe, so this is free to be the name.
        model.label = tag;
        // icon size [5 7] scaled directly from bus_expand's own
        // casper_library icon (50x76 px) -- see SKILL.md Step 3b
        x=standard_define([6 8.4],model,exprs,gr_i)
        x.graphics.in_label = iports_label;
        x.graphics.out_label = oports_label;
        x.graphics.style = 'shape=rectangle;fillColor=#90EE90';
        /* init exprs */
        x = init_exprs(x);
        debug_info('bus_expand block loaded...')
    end
endfunction

function [ports_index, ports_label] = bus_expand_create_iports(factor)
    ports_label = ['bus_in'];
    ports_index = [1];
endfunction

function [ports_index, ports_label] = bus_expand_create_oports(factor)
    ports_label = [];
    ports_index = [];
    for i = 1:factor
        // 1-based, matching casper_library bus_expand_init.m's out1, out2, ...
        ports_label = [ports_label, 'out' + string(i)];
        ports_index = [ports_index, i];
    end
endfunction

function [x] = bus_expand_update_ports(obj, bconfigfn)
    x = obj;
    bconfig = fromJSON(bconfigfn, 'file');
    p = bconfig('parameters');
    graphics = obj.graphics;
    exprs = graphics.exprs;
    model = obj.model;
    factor = strtod(p('ndivision'));
    evtin = [];
    evtout = [];
    [iports_index, iports_label] = bus_expand_create_iports(factor);
    [oports_index, oports_label] = bus_expand_create_oports(factor);
    // port I/O type: 1 = REAL (see set_io() docs); this mirrors wbfft/bus_create,
    // which don't distinguish port datatypes any further
    io_in = [iports_index; iports_index];
    io_out = [oports_index; oports_index];
    io_in_type = ones(1, length(iports_index));
    io_out_type = ones(1, length(oports_index));
    [model, graphics, ok] = set_io(model, graphics, list(io_in', io_in_type), list(io_out', io_out_type), evtin, evtout);
    model.in = iports_index;
    // input bus width is the sum of all output widths (it's being split)
    model.in2 = [sum(evstr(p('bit_division')))];
    model.out = oports_index;
    // one bit width per output, read straight from the "bit_division" vector
    // (e.g. "[8,8,8,8]"); NOT a uniform width * factor like wbfft's data ports
    model.out2 = evstr(p('bit_division'));
    graphics.in_label = iports_label;
    graphics.out_label = oports_label;
    graphics.style = 'shape=rectangle;fillColor=#90EE90';
    graphics.exprs = exprs;
    x.graphics = graphics;
    x.model = model;
endfunction
