// c_to_ri: Xcos block definition, PyQt6-mask pattern.
// Generated by casper_dsp/scripts/gen_sci_block.py -- review the port
// topology and TODOs below before relying on this in a real design.
function [x, y, typ] = c_to_ri(job, arg1, arg2)
    x=[];y=[];typ=[];
    select job
    case 'set' then
        x = arg1;
        export_exprs_to_tmpdir(x);
        bconfig = run_mask(x);
        x = update_exprs_from_tmpdir(x);
        x = c_to_ri_update_ports(x, bconfig);
    case 'define' then
        tag = 'c_to_ri';
        model = scicos_model();
        model.sim = list(tag, 4);
        model.blocktype = 'c';
        model.rpar = [];
        exprs = [];
        gr_i = [];
        // 'z' packs real+imag components together (CASPER complex bus
        // convention), so its width is 2*n_bits, not n_bits.
        model.in = [1];
        model.in2 = [36];
        model.out = [1, 2];
        model.out2 = [18, 18];
        // model.label doubles as the on-diagram display text (Scicos
        // aliases it with graphics.id); category is derived separately by
        // get_block_type.sci via file-probe, so this is free to be the name.
        model.label = tag;
        x=standard_define([4.8 4.8],model,exprs,gr_i)
        x.graphics.in_label = ['z'];
        x.graphics.out_label = ['re', 'im'];
        // block name (shown below the fill color) comes from the
        // "name" JSON key -- init_exprs populates exprs from the
        // template first, so exprs(1) is its default value here
        x = init_exprs(x);
        x.graphics.style = c_to_ri_build_style(x.graphics.exprs(1));
        debug_info('c_to_ri block loaded...')
    end
endfunction

function [style] = c_to_ri_build_style(name)
    // strip mxGraph's own style-string delimiters so a user-typed
    // name can never corrupt the rest of the style string
    name = strsubst(string(name), ';', '');
    name = strsubst(name, '=', '');
    style = 'shape=rectangle;fillColor=#90EE90;strokeColor=black;fontColor=black;fontSize=12;align=center;verticalAlign=top;verticalLabelPosition=bottom;noLabel=0;displayedLabel=' + name + ';whiteSpace=wrap;html=1;spacing=4;';
endfunction

function [x] = c_to_ri_update_ports(obj, bconfigfn)
    // fixed port count: only widths/labels change, no set_io() needed
    // (same approach as swreg_update_ports)
    x = obj;
    bconfig = fromJSON(bconfigfn, 'file');
    p = bconfig('parameters');
    graphics = x.graphics;
    model = x.model;
    n_bits = strtod(p('n_bits'));
    model.in = [1];
    model.in2 = [2*n_bits];
    model.out = [1, 2];
    model.out2 = [n_bits, n_bits];
    graphics.in_label = ['z'];
    graphics.out_label = ['re', 'im'];
    graphics.style = c_to_ri_build_style(p('name'));
    x.graphics = graphics;
    x.model = model;
endfunction
