// caddsub_dsp48e: Xcos block definition, PyQt6-mask pattern.
// Generated by casper_dsp/scripts/gen_sci_block.py -- review the port
// topology and TODOs below before relying on this in a real design.
function [x, y, typ] = caddsub_dsp48e(job, arg1, arg2)
    x=[];y=[];typ=[];
    select job
    case 'set' then
        x = arg1;
        export_exprs_to_tmpdir(x);
        bconfig = run_mask(x);
        x = update_exprs_from_tmpdir(x);
        x = caddsub_dsp48e_update_ports(x, bconfig);
    case 'define' then
        tag = 'caddsub_dsp48e';
        model = scicos_model();
        model.sim = list(tag, 4);
        model.blocktype = 'c';
        model.rpar = [];
        exprs = [];
        gr_i = [];
        model.in = [1, 2, 3, 4];
        model.in2 = [18, 18, 8, 8];
        model.out = [1, 2];
        model.out2 = [19, 19];
        // model.label doubles as the on-diagram display text (Scicos
        // aliases it with graphics.id); category is derived separately by
        // get_block_type.sci via file-probe, so this is free to be the name.
        model.label = tag;
        x=standard_define([8.4 8.4],model,exprs,gr_i)
        x.graphics.in_label = ['a_re', 'a_im', 'b_re', 'b_im'];
        x.graphics.out_label = ['c_re', 'c_im'];
        // block name (shown below the fill color) comes from the
        // "name" JSON key -- init_exprs populates exprs from the
        // template first, so exprs(1) is its default value here
        x = init_exprs(x);
        x.graphics.style = caddsub_dsp48e_build_style(x.graphics.exprs(1));
        debug_info('caddsub_dsp48e block loaded...')
    end
endfunction

function [style] = caddsub_dsp48e_build_style(name)
    // strip mxGraph's own style-string delimiters so a user-typed
    // name can never corrupt the rest of the style string
    name = strsubst(string(name), ';', '');
    name = strsubst(name, '=', '');
    style = 'shape=rectangle;fillColor=#90EE90;strokeColor=black;fontColor=black;fontSize=12;align=center;verticalAlign=top;verticalLabelPosition=bottom;noLabel=0;displayedLabel=' + name + ';whiteSpace=wrap;html=1;spacing=4;';
endfunction

function [x] = caddsub_dsp48e_update_ports(obj, bconfigfn)
    // fixed port count: only widths/labels change, no set_io() needed
    // (same approach as swreg_update_ports)
    x = obj;
    bconfig = fromJSON(bconfigfn, 'file');
    p = bconfig('parameters');
    graphics = x.graphics;
    model = x.model;
    n_bits_a = strtod(p('n_bits_a'));
    bin_pt_a = strtod(p('bin_pt_a'));
    n_bits_b = strtod(p('n_bits_b'));
    bin_pt_b = strtod(p('bin_pt_b'));
    // n_bits_out mirrors casper_library/caddsub_dsp48e_init.m: with full
    // precision it grows to fit both inputs' integer+fractional ranges
    // plus a carry bit; otherwise it's just the user's n_bits_c/bin_pt_c.
    if p('full_precision') == 'on' then
        max_non_frac = max(n_bits_a - bin_pt_a, n_bits_b - bin_pt_b);
        max_bin_pt = max(bin_pt_a, bin_pt_b);
        n_bits_out = max_non_frac + max_bin_pt + 1;
    else
        n_bits_out = strtod(p('n_bits_c'));
    end
    model.in = [1, 2, 3, 4];
    model.in2 = [n_bits_a, n_bits_a, n_bits_b, n_bits_b];
    model.out = [1, 2];
    model.out2 = [n_bits_out, n_bits_out];
    graphics.in_label = ['a_re', 'a_im', 'b_re', 'b_im'];
    graphics.out_label = ['c_re', 'c_im'];
    graphics.style = caddsub_dsp48e_build_style(p('name'));
    x.graphics = graphics;
    x.model = model;
endfunction
