// complex_addsub: Xcos block definition, PyQt6-mask pattern.
// Generated by casper_dsp/scripts/gen_sci_block.py -- review the port
// topology and TODOs below before relying on this in a real design.
function [x, y, typ] = complex_addsub(job, arg1, arg2)
    x=[];y=[];typ=[];
    select job
    case 'set' then
        x = arg1;
        export_exprs_to_tmpdir(x);
        bconfig = run_mask(x);
        x = update_exprs_from_tmpdir(x);
        x = complex_addsub_update_ports(x, bconfig);
    case 'define' then
        tag = 'complex_addsub';
        model = scicos_model();
        model.sim = list(tag, 4);
        model.blocktype = 'c';
        model.rpar = [];
        exprs = [];
        gr_i = [];
        // a/b/sum/diff are complex (real+imag packed): width 2*bit_width.
        model.in = [1, 2];
        model.in2 = [36, 36];
        model.out = [1, 2];
        model.out2 = [36, 36];
        // model.label doubles as the on-diagram display text (Scicos
        // aliases it with graphics.id); category is derived separately by
        // get_block_type.sci via file-probe, so this is free to be the name.
        model.label = tag;
        x=standard_define([7 7],model,exprs,gr_i)
        x.graphics.in_label = ['a', 'b'];
        x.graphics.out_label = ['sum', 'diff'];
        x.graphics.style = 'shape=rectangle;fillColor=#90EE90';
        /* init exprs */
        x = init_exprs(x);
        debug_info('complex_addsub block loaded...')
    end
endfunction

function [x] = complex_addsub_update_ports(obj, bconfigfn)
    // fixed port count: only widths/labels change, no set_io() needed
    // (same approach as swreg_update_ports)
    x = obj;
    bconfig = fromJSON(bconfigfn, 'file');
    p = bconfig('parameters');
    graphics = x.graphics;
    model = x.model;
    w = 2*strtod(p('bit_width'));
    model.in = [1, 2];
    model.in2 = [w, w];
    model.out = [1, 2];
    model.out2 = [w, w];
    graphics.in_label = ['a', 'b'];
    graphics.out_label = ['sum', 'diff'];
    graphics.style = 'shape=rectangle;fillColor=#90EE90';
    x.graphics = graphics;
    x.model = model;
endfunction
