// complex_conj: Xcos block definition, PyQt6-mask pattern.
// Generated by casper_dsp/scripts/gen_sci_block.py -- review the port
// topology and TODOs below before relying on this in a real design.
function [x, y, typ] = complex_conj(job, arg1, arg2)
    x=[];y=[];typ=[];
    select job
    case 'set' then
        x = arg1;
        export_exprs_to_tmpdir(x);
        bconfig = run_mask(x);
        x = update_exprs_from_tmpdir(x);
        x = complex_conj_update_ports(x, bconfig);
    case 'define' then
        tag = 'complex_conj';
        model = scicos_model();
        model.sim = list(tag, 4);
        model.blocktype = 'c';
        model.rpar = [];
        exprs = [];
        gr_i = [];
        // 'z'/'z_conj' pack n_inputs simultaneous complex streams, each
        // real+imag, into one bus: width = 2*n_inputs*n_bits.
        model.in = [1];
        model.in2 = [36];
        model.out = [1];
        model.out2 = [36];
        // model.label doubles as the on-diagram display text (Scicos
        // aliases it with graphics.id); category is derived separately by
        // get_block_type.sci via file-probe, so this is free to be the name.
        model.label = tag;
        x=standard_define([8.4 8.4],model,exprs,gr_i)
        x.graphics.in_label = ['z'];
        x.graphics.out_label = ['z_conj'];
        x.graphics.style = 'shape=rectangle;fillColor=#90EE90';
        /* init exprs */
        x = init_exprs(x);
        debug_info('complex_conj block loaded...')
    end
endfunction

function [x] = complex_conj_update_ports(obj, bconfigfn)
    // fixed port count: only widths/labels change, no set_io() needed
    // (same approach as swreg_update_ports)
    x = obj;
    bconfig = fromJSON(bconfigfn, 'file');
    p = bconfig('parameters');
    graphics = x.graphics;
    model = x.model;
    w = 2*strtod(p('n_inputs'))*strtod(p('n_bits'));
    model.in = [1];
    model.in2 = [w];
    model.out = [1];
    model.out2 = [w];
    graphics.in_label = ['z'];
    graphics.out_label = ['z_conj'];
    graphics.style = 'shape=rectangle;fillColor=#90EE90';
    x.graphics = graphics;
    x.model = model;
endfunction
