// fixed_to_float: Xcos block definition, PyQt6-mask pattern.
// Generated by casper_dsp/scripts/gen_sci_block.py -- review the port
// topology and TODOs below before relying on this in a real design.
function [x, y, typ] = fixed_to_float(job, arg1, arg2)
    x=[];y=[];typ=[];
    select job
    case 'set' then
        x = arg1;
        export_exprs_to_tmpdir(x);
        bconfig = run_mask(x);
        x = update_exprs_from_tmpdir(x);
        x = fixed_to_float_update_ports(x, bconfig);
    case 'define' then
        tag = 'fixed_to_float';
        model = scicos_model();
        model.sim = list(tag, 4);
        model.blocktype = 'c';
        model.rpar = [];
        exprs = [];
        gr_i = [];
        // 'din'/'dout' are buses of num_vec elements: width = n_bits_in*num_vec
        // in, (32 or 64, per float_type)*num_vec out.
        model.in = [1];
        model.in2 = [18];
        model.out = [1];
        model.out2 = [32];
        // model.label doubles as the on-diagram display text (Scicos
        // aliases it with graphics.id); category is derived separately by
        // get_block_type.sci via file-probe, so this is free to be the name.
        model.label = tag;
        x=standard_define([8.4 8.4],model,exprs,gr_i)
        x.graphics.in_label = ['din'];
        x.graphics.out_label = ['dout'];
        x.graphics.style = 'shape=rectangle;fillColor=#90EE90';
        /* init exprs */
        x = init_exprs(x);
        debug_info('fixed_to_float block loaded...')
    end
endfunction

function [x] = fixed_to_float_update_ports(obj, bconfigfn)
    // fixed port count: only widths/labels change, no set_io() needed
    // (same approach as swreg_update_ports)
    x = obj;
    bconfig = fromJSON(bconfigfn, 'file');
    p = bconfig('parameters');
    graphics = x.graphics;
    model = x.model;
    num_vec = strtod(p('num_vec'));
    if p('float_type') == 'Double' then
        float_width = 64;
    else
        float_width = 32;
    end
    model.in = [1];
    model.in2 = [strtod(p('n_bits_in')) * num_vec];
    model.out = [1];
    model.out2 = [float_width * num_vec];
    graphics.in_label = ['din'];
    graphics.out_label = ['dout'];
    graphics.style = 'shape=rectangle;fillColor=#90EE90';
    x.graphics = graphics;
    x.model = model;
endfunction
