// shifter_unit: Xcos block definition, PyQt6-mask pattern.
// Generated by casper_dsp/scripts/gen_sci_block.py -- review the port
// topology and TODOs below before relying on this in a real design.
function [x, y, typ] = shifter_unit(job, arg1, arg2)
    x=[];y=[];typ=[];
    select job
    case 'set' then
        x = arg1;
        export_exprs_to_tmpdir(x);
        bconfig = run_mask(x);
        x = update_exprs_from_tmpdir(x);
        x = shifter_unit_update_ports(x, bconfig);
    case 'define' then
        tag = 'shifter_unit';
        model = scicos_model();
        model.sim = list(tag, 4);
        model.blocktype = 'c';
        model.rpar = [];
        exprs = [];
        gr_i = [];
        // 'pin' (port 3) carries the full parent parallel bus, of which
        // this unit only consumes the [pin_offset : pin_offset+data_width-1]
        // slice -- so its port width has to be at least pin_offset+data_width,
        // not just data_width (see parallel_to_serial_converter_init.m).
        model.in = [1, 2, 3, 4];
        model.in2 = [1, 16, 0 + 16, 1];
        model.out = [1];
        model.out2 = [16];
        // model.label doubles as the on-diagram display text (Scicos
        // aliases it with graphics.id); category is derived separately by
        // get_block_type.sci via file-probe, so this is free to be the name.
        model.label = tag;
        x=standard_define([6 4.8],model,exprs,gr_i)
        x.graphics.in_label = ['sel', 'prev', 'pin', 'reg_en'];
        x.graphics.out_label = ['dout'];
        // block name (shown below the fill color) comes from the
        // "name" JSON key -- init_exprs populates exprs from the
        // template first, so exprs(1) is its default value here
        x = init_exprs(x);
        x.graphics.style = shifter_unit_build_style(x.graphics.exprs(1));
        debug_info('shifter_unit block loaded...')
    end
endfunction

function [style] = shifter_unit_build_style(name)
    // strip mxGraph's own style-string delimiters so a user-typed
    // name can never corrupt the rest of the style string
    name = strsubst(string(name), ';', '');
    name = strsubst(name, '=', '');
    style = 'shape=rectangle;fillColor=#90EE90;strokeColor=black;fontColor=black;fontSize=12;align=center;verticalAlign=top;verticalLabelPosition=bottom;noLabel=0;displayedLabel=' + name + ';whiteSpace=wrap;html=1;spacing=4;';
endfunction

function [x] = shifter_unit_update_ports(obj, bconfigfn)
    // fixed port count: only widths/labels change, no set_io() needed
    // (same approach as swreg_update_ports)
    x = obj;
    bconfig = fromJSON(bconfigfn, 'file');
    p = bconfig('parameters');
    graphics = x.graphics;
    model = x.model;
    data_width = strtod(p('data_width'));
    pin_offset = strtod(p('pin_offset'));
    model.in = [1, 2, 3, 4];
    model.in2 = [1, data_width, pin_offset + data_width, 1];
    model.out = [1];
    model.out2 = [data_width];
    graphics.in_label = ['sel', 'prev', 'pin', 'reg_en'];
    graphics.out_label = ['dout'];
    graphics.style = shifter_unit_build_style(p('name'));
    x.graphics = graphics;
    x.model = model;
endfunction
