// spect_power: Xcos block definition, PyQt6-mask pattern.
// Generated by casper_dsp/scripts/gen_sci_block.py -- review the port
// topology and TODOs below before relying on this in a real design.
function [x, y, typ] = spect_power(job, arg1, arg2)
    x=[];y=[];typ=[];
    select job
    case 'set' then
        x = arg1;
        export_exprs_to_tmpdir(x);
        bconfig = run_mask(x);
        x = update_exprs_from_tmpdir(x);
        x = spect_power_update_ports(x, bconfig);
    case 'define' then
        tag = 'spect_power';
        model = scicos_model();
        model.sim = list(tag, 4);
        model.blocktype = 'c';
        model.rpar = [];
        exprs = [];
        gr_i = [];
        [iports_index, iports_label] = spect_power_create_iports(1);
        model.in = iports_index;
        model.in2 = [18*ones(1, 1)];
        [oports_index, oports_label] = spect_power_create_oports(1);
        model.out = oports_index;
        model.out2 = [18*ones(1, 1)];
        // model.label doubles as the on-diagram display text (Scicos
        // aliases it with graphics.id); category is derived separately by
        // get_block_type.sci via file-probe, so this is free to be the name.
        model.label = tag;
        x=standard_define([7 7],model,exprs,gr_i)
        x.graphics.in_label = iports_label;
        x.graphics.out_label = oports_label;
        x.graphics.style = 'shape=rectangle;fillColor=#90EE90';
        /* init exprs */
        x = init_exprs(x);
        debug_info('spect_power block loaded...')
    end
endfunction

function [ports_index, ports_label] = spect_power_create_iports(factor)
    ports_label = [];
    ports_index = [];
    for i = 1:factor
        ports_label = [ports_label, 'in' + string(i - 1)];
        ports_index = [ports_index, 0 + (i - 1) * 1 + 1];
    end
endfunction

function [ports_index, ports_label] = spect_power_create_oports(factor)
    ports_label = [];
    ports_index = [];
    for i = 1:factor
        ports_label = [ports_label, 'power' + string(i - 1)];
        ports_index = [ports_index, 0 + (i - 1) * 1 + 1];
    end
endfunction

function [x] = spect_power_update_ports(obj, bconfigfn)
    x = obj;
    bconfig = fromJSON(bconfigfn, 'file');
    p = bconfig('parameters');
    graphics = obj.graphics;
    exprs = graphics.exprs;
    model = obj.model;
    factor = strtod(p('n_inputs'));
    evtin = [];
    evtout = [];
    [iports_index, iports_label] = spect_power_create_iports(factor);
    [oports_index, oports_label] = spect_power_create_oports(factor);
    // port I/O type: 1 = REAL (see set_io() docs); this mirrors wbfft/bus_expand,
    // which don't distinguish port datatypes any further
    io_in = [iports_index; iports_index];
    io_out = [oports_index; oports_index];
    io_in_type = ones(1, length(iports_index));
    io_out_type = ones(1, length(oports_index));
    [model, graphics, ok] = set_io(model, graphics, list(io_in', io_in_type), list(io_out', io_out_type), evtin, evtout);
    model.in = iports_index;
    model.in2 = [strtod(p('bitwidth'))*ones(1, factor)];
    model.out = oports_index;
    model.out2 = [strtod(p('bitwidth'))*ones(1, factor)];
    graphics.in_label = iports_label;
    graphics.out_label = oports_label;
    graphics.style = 'shape=rectangle;fillColor=#90EE90';
    graphics.exprs = exprs;
    x.graphics = graphics;
    x.model = model;
endfunction
