# Form implementation for the Complex Add/Sub mask dialog.
# Hand-generated by casper_dsp/scripts/gen_block_gui.py to match the layout
# in ui/complex_addsub.ui -- if PyQt6/pyuic6 is available, regenerate with:
#   pyuic6 ui/complex_addsub.ui -o complex_addsub_ui.py
# and keep both in sync by hand otherwise.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(560, 310)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)

        self.desc_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.desc_label.setWordWrap(True)
        self.desc_label.setObjectName("desc_label")
        self.verticalLayout.addWidget(self.desc_label)

        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout.setColumnStretch(1, 1)
        self.label_name = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_name.setObjectName("label_name")
        self.label_name.setWordWrap(True)
        self.label_name.setFixedWidth(444)
        self.gridLayout.addWidget(self.label_name, 0, 0, 1, 1)
        self.name = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 0, 1, 1, 2)
        self.label_bit_width = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_bit_width.setObjectName("label_bit_width")
        self.label_bit_width.setWordWrap(True)
        self.label_bit_width.setFixedWidth(101)
        self.gridLayout.addWidget(self.label_bit_width, 1, 0, 1, 1)
        self.bit_width = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.bit_width.setObjectName("bit_width")
        self.bit_width.setRange(1, 128)
        self.gridLayout.addWidget(self.bit_width, 1, 1, 1, 2)
        self.label_add_latency = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_add_latency.setObjectName("label_add_latency")
        self.label_add_latency.setWordWrap(True)
        self.label_add_latency.setFixedWidth(101)
        self.gridLayout.addWidget(self.label_add_latency, 2, 0, 1, 1)
        self.add_latency = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.add_latency.setObjectName("add_latency")
        self.add_latency.setRange(0, 32)
        self.gridLayout.addWidget(self.add_latency, 2, 1, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.buttonLayout.addItem(spacerItem)
        self.button_apply = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_apply.setObjectName("button_apply")
        self.buttonLayout.addWidget(self.button_apply)
        self.button_ok = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_ok.setObjectName("button_ok")
        self.buttonLayout.addWidget(self.button_ok)
        self.button_cancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_cancel.setObjectName("button_cancel")
        self.buttonLayout.addWidget(self.button_cancel)
        self.verticalLayout.addLayout(self.buttonLayout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Complex Add/Sub"))
        self.title_label.setText(_translate("MainWindow", "Complex Add/Sub"))
        self.desc_label.setText(_translate("MainWindow", "Adds and subtracts the complex inputs. If a = w + ix, b = y + iz then a+b = (w+y)/2 + i(x-z)/2 and a-b = (x+z)/2 + i(y-w)/2"))
        self.label_name.setText(_translate("MainWindow", "Block name"))
        self.name.setToolTip(_translate("MainWindow", "A name you choose for this block instance, e.g. to note what it's used for in this design. Shown below the block on the diagram."))
        self.label_bit_width.setText(_translate("MainWindow", "Bit Width"))
        self.label_add_latency.setText(_translate("MainWindow", "Add Latency"))
        self.button_apply.setText(_translate("MainWindow", "Apply"))
        self.button_ok.setText(_translate("MainWindow", "OK"))
        self.button_cancel.setText(_translate("MainWindow", "Cancel"))
